### ISSUE TITLE
Multi Thread Download

### ISSUE THREAD

**Issue by clansty** [ninxsoft/Mist#104]
### :bulb: Description

Would you support multi thread downloading for the large files such as the InstallAssistant.pkg?

### :white_check_mark: Proposed solution

This will boost the download speed in my environment

### :adhesive_bandage: Alternatives Solutions + Workarounds

Wait more time

### :information_source: Additional context

no

**Comment by ninxsoft** [comment]
Mist uses [URLSession](https://developer.apple.com/documentation/foundation/urlsession), which I believe does not support segmented downloads.

Having a quick look online, it appears there are projects online that support such a feature, such as [aria2](https://github.com/aria2/aria2).

While I do not have plans to support such a feature (or rather, replace my URLSession logic with a framework I am not familiar with), I would be more than happy to review any potential Pull Requests that come this way 👍
