### ISSUE TITLE
Installers for 10.9 is missing

### ISSUE THREAD

**Issue by hronro** [ninxsoft/Mist#105]
I can see that older OSes like 10.8.5 and 10.7.5 are available, but I cannot find 10.9 Mavericks in the list.

Is there a specific reason why 10.9 is not supported?

**Comment by ninxsoft** [comment]
Marking as duplicate of https://github.com/ninxsoft/Mist/issues/60:

> Apple does not provide a download link for OS X Mavericks 10.9:
>
> https://support.apple.com/en-us/HT211683
