### ISSUE TITLE
I made a Guide for Mist to help Non-Tech People, with step by step screenshots. up next for Apple-Silicon

### ISSUE THREAD

**Issue by ayushere** [ninxsoft/Mist#107]
I wrote it as a Series for my Hackintosh guide but it might help people here also.

https://kextcache.com/guide-making-bootable-macos-sonoma-usb-using-mist/
![kextthumb](https://github.com/ninxsoft/Mist/assets/44045943/c0a124f8-8687-4e90-8eaf-205c85f3d39c)

**Comment by ninxsoft** [comment]
Thank you so much!
