### ISSUE TITLE
Mist Log File

### ISSUE THREAD

**Issue by Chilternburt** [ninxsoft/Mist#108]
### :bulb: Description

I'd like to see some form of logging as Mist goes through the process, so that when failures occur it's easier to troubleshoot the issue

### :white_check_mark: Proposed solution

Mist writes a log to either /Library/Logs or ~/Library/Logs

### :adhesive_bandage: Alternatives Solutions + Workarounds

Some apps have the option to show the log live in a window, kinda like tha macOS installer log

### :information_source: Additional context

- Would you also like to see this implemented in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x: Yes for sure
- Links to 3rd-party tools / references / documentation
- Screenshots / diagrams that help explain the feature request

**Comment by Honestpuck** [comment]
Can I add a plus one to this. I've got a weird problem downloading Firmware and no way to check what's happening.

**Comment by ninxsoft** [comment]
WIP:

![Logs](https://github.com/ninxsoft/Mist/assets/4812595/55946efd-da50-43bd-859f-c401b74c209b)
