### ISSUE TITLE
CLI and GUI packages have same bundle ID

### ISSUE THREAD

**Issue by nider** [ninxsoft/Mist#11]
Both packages have the bundle ID `com.ninxsoft.pkg.mist` I noticed this when I downloaded the GUI package which has version 0.2 and the receipts on my Mac said I already had installed version 1.6.1.

Each package should have a unique bundle ID, which will also help with tools that manage installations and use the bundle ID and version to determine whether an update needs to be installed

**Comment by ninxsoft** [comment]
Hi @nider, this was fixed in https://github.com/ninxsoft/mist-cli/commit/8841db092b9659543a71132840b4a9abc4790809, I just haven't gotten around to pushing out a new release.

Should be able to cut a new version soon 👍

**Comment by ninxsoft** [comment]
This is now fixed!

You can grab the latest version of mist from the [Releases](https://github.com/ninxsoft/mist-cli/releases) page.
