### ISSUE TITLE
Add option for naming file in a specific manner

### ISSUE THREAD

**Issue by smithjw** [ninxsoft/Mist#11]
Would be great if there was a flag to allow the naming of the outputted file rather than following the default naming Mist currently uses.

**Comment by ninxsoft** [comment]
Sounds like a great idea, I'm proposing the removal of the `--output` flag, and updating the following flags:

* `--application <path/to/app>`: if present, generate an app bundle
* `--image <path/to/dmg>`: if present, generate a disk image
* `--package <path/to/pkg>`: if present, generate an installer package
* `--zip <path/to/zip>`: if present, generate a zip archive

For all options, create the parent folder structure if it does not exist.

Thoughts?

**Comment by smithjw** [comment]
Yeah, I like these options. If it's not too much work, just specifying the folder-path should use whatever your default naming scheme is, but if someone defined the full path, then that name is used.

**Comment by ninxsoft** [comment]
Settling on the following final decisions:

1. `-o | --output-directory` specifies the directory where the file(s) will be output
2. `-f, --filename-template` specifies the filename template. The following variables will be substituted with dynamic values, for example:
    * `%NAME%` will be replaced by `macOS Big Sur`
    * `%VERSION%` will be replaced by `11.4`
    * `%BUILD%` will be replaced by `20F71`
    * File extensions will be added automatically when the `--application`, `--image`, `--package` or `--zip` flags are used
    * Default filename template will be `Install %NAME% %VERSION%-%BUILD%`, which in this example would convert to `Install macOS Big Sur 11.4-20F71.app`

**Comment by ninxsoft** [comment]
Added in c762d6170bdcf8e1fe40845b59ca4d458f8dad19
