### ISSUE TITLE
Is there a way to do cleanup manually after failed download

### ISSUE THREAD

**Issue by myang80** [ninxsoft/Mist#110]
Hello,

Thanks for providing this tool! I have a few failures when I try to download MacOS, and the temporary download files take some space. Is there a way I can do the cleanup manually?

Thank you!

**Comment by ninxsoft** [comment]
@myang80, @F1248 is correct - downloaded files can be removed via **Settings > Installers > Cache downloads**

For partial files that failed to download successfully, they live somewhere in `/private/var/folders/..`. Restarting macOS will get rid of those 👍
