### ISSUE TITLE
Add a "Copy URL to Clipboard" feature

### ISSUE THREAD

**Issue by BigMacAdmin** [ninxsoft/Mist#112]
### :bulb: Description

Add "Copy URL to Clipboard" as a button next to the download buttons.

### :white_check_mark: Proposed solution

Get the download URL from whichever mechanism Mist is already using and copy that value to the users clipboard.

### :adhesive_bandage: Alternatives Solutions + Workarounds

Nindi can continue to manually do this for each and every user that asks for it on Slack! /sarcasm
https://macadmins.slack.com/archives/CF0CFM5B7/p1704686177867719

### :information_source: Additional context

- Would you also like to see this implemented in [mist-cli](https://github.com/ninxsoft/mist-cli)? 
- Maybe. It could be a "Link only" mode instead of "download" or "list"
- :white_check_mark: / :x:
- Links to 3rd-party tools / references / documentation
- Screenshots / diagrams that help explain the feature request

**Comment by ninxsoft** [comment]
I'm leaning towards adding the URLs for firmwares **only**, as installers actually comprise of multiple files (pkgs, plists, checksum validation files, etc.)

- **For Mist.app:** Add a button to copy to clipboard
- **For mist-cli:** Add to the export output when running `mist list`

**Comment by ninxsoft** [comment]
Looking good 🥳

![Copy 01](https://github.com/ninxsoft/Mist/assets/4812595/e9e7b650-8b86-49b2-836c-4350b4603e47)

![Copy 02](https://github.com/ninxsoft/Mist/assets/4812595/b2420028-f489-4d0d-be2d-749e76226f6d)
