### ISSUE TITLE
Use IPSW to create bootable installer.

### ISSUE THREAD

**Issue by Honestpuck** [ninxsoft/Mist#113]
### :bulb: Description

I would like to be able to use an IPSW already downloaded to create the bootable installer.

### :white_check_mark: Proposed solution

I would like a diaolg asking me to select an IPSW or continue to come up after you hit the button in the OS list.

### :information_source: Additional context

- Would you also like to see this implemented in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark:

**Comment by ninxsoft** [comment]
@Honestpuck I'm 99% certain IPSWs cannot be used to create a bootable installer, either as an ISO or onto a USB stick.

Do you have any resources that explain how to do this?

**Comment by Honestpuck** [comment]
Nindi,

No, I don't. After doing some looking I agree with you, it ain't possible.

**Comment by kopyl** [comment]
@ninxsoft do you know any reliable way to download macOS installer for an older macOS version which can be used to created a bootable disk?

Something which works with this command:
```
sudo /Applications/Install\ macOS\ Ventura.app/Contents/Resources/createinstallmedia --volume /Volumes/Install\ macOS\ Sequoia/
```
