### ISSUE TITLE
Download multiple Images

### ISSUE THREAD

**Issue by dschiller** [ninxsoft/Mist#116]
### :bulb: Description

as i am working as a qa engineer i need to download multiple OSes. it would be beneficial to be able to checkbox select multiple OSes and download them at ones.

### :white_check_mark: Proposed solution

i would like to see a checkbox next to each OS in order to download multiple files at once.

### :adhesive_bandage: Alternatives Solutions + Workarounds

a workaround is to wait for each doenload and then load them in a sequence manually.

### :information_source: Additional context

- Would you also like to see this implemented in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x:
- Links to 3rd-party tools / references / documentation
- Screenshots / diagrams that help explain the feature request

**Comment by ninxsoft** [comment]
@dschiller have you looked at [mist-cli](https://github.com/ninxsoft/mist-cli) as an option? `mist-cli` was written with a semi-goal of being able to be scripted / automated. You could in theory:

1. Run `mist list <subcommand>` to retrieve a list of Firmwares / Installers
1. Iterate through that list and `mist download <subcommand>` each individual Firmware / Installer

**Comment by dschiller** [comment]
Thank you a lot Nindi, i was not aware of mist-cli - should have read the "Additional context" section better.
