### ISSUE TITLE
Please make Mist work on obsolete OSes with expired certificates.

### ISSUE THREAD

**Issue by rin67630** [ninxsoft/Mist#118]
### :bulb: Description

Mist should run on old macOS like Lion. 
The internet recovery provides e.g Lion for 2012 Macs.
From there, you practically have no way to download a better OS since the certificates are expired and you can't https:// correctly nor get something from the Store.

In the history one can read: 

Added support for the following legacy operating systems:

    macOS Sierra 10.12.6
    OS X El Capitan 10.11.6
    OS X Yosemite 10.10.5
    OS X Mountain Lion 10.8.5
    Mac OS X Lion 10.7.5
    Thanks [n8felton](https://github.com/n8felton)!
    
  But "support means the ability to download the OLd OS from a newer one, not that Mist will run on those OSes.

**Comment by bslatyer** [comment]
Hi @rin67630,

I don't believe this will get implemented because legacy OSes do not support the newer APIs and frameworks found in the current macOS versions.

The lowest OS that Mist will run on is macOS Monterey 12.x

This feature would most likely require a complete code rebuild to even remotely support this.

But I think @ninxsoft would have more insight into this 😉

Thanks,

Braeden

**Comment by ninxsoft** [comment]
@rin67630 your assumption about the release notes history is correct - the "support" refers to versions of macOS that can be downloaded, not versions of macOS where Mist the application is compatible.

As much as I would love Mist to run on older platforms, this is unfortunately not an option for the following reasons:

- The Mist user interface is build using [SwiftUI](https://developer.apple.com/xcode/swiftui/), which is only compatible with **macOS Catalina 10.15** and later
- Each year Apple introduces new features and capabilities to SwiftUI, some of which Mist has adopted. This is why Mist is only supported on **macOS Monterey 12.0** and later
- Writing entirely different user interface code to support legacy versions of macOS would be difficult to maintain, especially considering I don't use older operating systems and any testing would be trivial at best

That being said, Apple _does_ in fact offer download links for older versions of macOS, outside of the Mac App Store: [How to download and install macOS
](https://support.apple.com/en-us/102662)

These are the same links Mist uses internally 👍

**Comment by jelabarre59** [comment]
So this utility is inherently useless
