### ISSUE TITLE
Mist display wrong Beta version

### ISSUE THREAD

**Issue by Hanashi** [ninxsoft/Mist#12]
Mist shows currently macOS Ventura 13.0 Beta Build 22A5352e from 2022-09-21, but newest beta version is build 22A5358e from yesterday (2022-09-27).

**Comment by ninxsoft** [comment]
@Hanashi Mist grabs all available macOS Installers from Apple Software Update Catalogs (SUCatalogs). You can see these listed on the **Installers** pane in the Mist app **Settings**:

![SUCatalogs](https://user-images.githubusercontent.com/4812595/192767556-27e7e554-ced1-4c29-8957-3de578d8847c.png)

Apple usually updates these SUCatalogs within a day or two of release, so try again in a bit and you should be able to grab the latest version 👍.

Alternatively, you can edit the list of Catalog URLs as required (different SUCatalogs exist out in the wild).

**Comment by ninxsoft** [comment]
macOS Ventura 13.0 build 22A5358e is now available:

![22A5358e](https://user-images.githubusercontent.com/4812595/193017366-8603e53a-e41c-4dc9-a704-f224ce443885.png)
