### ISSUE TITLE
Mist ver 0.5 / 0.6 / 0.1 not compatible with OSX El Capitan

### ISSUE THREAD

**Issue by fuse8fuse** [ninxsoft/Mist#125]
### :beetle: Description

Describe clearly and concisely what is not working.

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
1. Click on ...
1. Wait for ...
1. Observe error

### :white_check_mark: Expected Behaviour

Describe what should be happening (ie. the happy path).

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): **VERSION**
- macOS Version (`sw_vers`): **VERSION BUILD**
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: **MODEL_IDENTIFIER**
  - Chip : **CHIP**

### :camera: Screenshots

If applicable, add screenshots to help explain the bug.

### :information_source: Additional context

- Is this also a bug in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x:
  - Provide links to GitHub Issues
- Links to 3rd-party tools / references / documentation

**Comment by nstrauss** [comment]
https://github.com/ninxsoft/Mist?tab=readme-ov-file#build-requirements

> Runs on macOS Monterey 12.0 and later.

You're asking for support for an OS last patched in 2018. 8 major versions behind current. I wouldn't call this a bug, and would close out the issue.

**Comment by nstrauss** [comment]
> Fixed a bug where macOS Sierra 10.12.6, OS X El Capitan 10.11.6 and OS X Yosemite 10.10.5 would fail to download.

Mist can _download_ those OS versions but not does _run_ on them.

**Comment by ninxsoft** [comment]
@fuse8fuse jus re-iterating what @nstrauss mentioned, Mist supports the _downloading_ of older versions of macOS, but requires **macOS Monterey 12** or later to actually run the app.

Will go ahead and close this ticket, thanks!
