### ISSUE TITLE
Optionally Disable Logging 

### ISSUE THREAD

**Issue by smithjw** [ninxsoft/Mist#13]
When running Mist from a management tool like Jamf, the output is truncated because of how verbose Mist is. It would be great to have a feature flag to turn this off, or at least, log less.

![Screen Shot 2021-04-29 at 2 31 08 pm](https://user-images.githubusercontent.com/916389/116502693-9085ac00-a8f7-11eb-8b77-5de695d7043a.png)

**Comment by ninxsoft** [comment]
I agree! I am currently looking at a few options to output less verbose messages.

Will also factor in an option to suppress output altogether.

Stay tuned...

**Comment by ninxsoft** [comment]
Message verbosity has been reduced, and the download progress has been removed as it was really buggy!

Fixed in 4673793db02de149e50f08e9b59656aa3c6140b6 and 38e25127c811c658a1a74c9d44fa1af4e27265ee
