### ISSUE TITLE
DMG is created but only Read and need Read and Write

### ISSUE THREAD

**Issue by AnaCarolina1980** [ninxsoft/Mist#130]
Hi. Nice and fantastic tool. Thanks for that.

DMG is created but only "Read" and need "Read and Write" to edit some things if need.
![bug](https://github.com/ninxsoft/Mist/assets/70116289/cbbbd9a3-dea5-4e87-ac73-00f011e57c0d)
Thank you!

**Comment by grahampugh** [comment]
That's certainly not a bug. I'm struggling to see the use case but I cannot see how it could predicted how much extra space you would need in your DMG to add extra stuff. Therefore in my opinion it would make sense for you to download the installer app in Mist, create your own read/write DMG of whatever size you need, and then copy the app and other stuff into it.

**Comment by AnaCarolina1980** [comment]
Sorry, but this is very useful for those who work with this and need to create an image where we can add some more files, copy files to the root of the .dmg, for example.

**Comment by ninxsoft** [comment]
@AnaCarolina1980 by design Mist attempts to create DMGs / ISOs / PKGs as close to the app installer as possible, without modification where possible.

I propose creating a writable disk image by first creating a standard disk image via Mist or `createinstallmedia`, then using the `hdiutil` command to convert said disk image:

```shell
hdiutil convert -help

hdiutil convert: convert an image into a different format
Usage:	hdiutil convert -format <format> -o <outfile> <image>
	Image Formats:
	    UDRO - read-only
	    UDCO - compressed (ADC)
	    UDZO - compressed
	    UDBZ - compressed (bzip2), deprecated
	    ULFO - compressed (lzfse)
	    ULMO - compressed (lzma)
	    UFBI - entire device
	    IPOD - iPod image
	    UDSB - sparsebundle
	    UDSP - sparse
	    UDRW - read/write
	    UDTO - DVD/CD master

	Convert options:
	    -ov		overwrite target file(s) if it already exists
	    -align [<sector alignment>]	[4 aka 2K]
	    -pmap
	    -segmentSize < ?? | ??b | ??k | ??m | ??g | ??t | ??p | ??e > (deprecated)
	        (blocks, bytes, kilobytes, megabytes, gigabytes, terabytes, petabytes, exabytes)
	    -tasks <task count>		[12]

	Common options:
	    -encryption <crypto method>
	    	AES-128 - 128-bit AES encryption (recommended)
	    	AES-256 - 256-bit AES encryption (more secure, but slower)
	    -stdinpass
	    -agentpass
	    -certificate <path-to-cert-file>
	    -srcimagekey <key>=<value>	(-imagekey is a synonym)
	    -tgtimagekey <key>=<value>
	    -shadow <shadowfile>
	    -insecurehttp
	    -cacert <file | dir>
	    -plist
	    -puppetstrings
	    -verbose
	    -debug
	    -quiet
```

This will allow you to convert the read-only disk image to read-write :+1:

**Comment by AnaCarolina1980** [comment]
Thanks for that! 

hdiutil convert -format UDRW xxxx.dmg -o xxxxnew.dmg

Solved!
