### ISSUE TITLE
Two App Bundles are produced when downloading Catalina 10.15.7_19H15

### ISSUE THREAD

**Issue by A00736470** [ninxsoft/Mist#135]
### :beetle: Description

I recently tried to download the Catalina app for installation on an older computer but noticed that two app bundles get produced.  The first is macOS Catalina 10.15.7_19H15.app, downloaded to where I specified.  The second is macOS Catalina.app, located in the Applications folder with a prohibited symbol.  

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
2. Click on download macOS Catalina 10.15.7 (19H15)
3. Click Continue on the compatibility warning
4. Keep default export type as Application and select the Downloads folder

### :white_check_mark: Expected Behaviour

I was expecting one .app file like when downloading from the App Store.

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): 0.20
- macOS Version (`sw_vers`): 13.6.7
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: Mac14,9
  - Chip : M2 Pro

### :camera: Screenshots

<img width="604" alt="image" src="https://github.com/user-attachments/assets/73dc6e2d-7696-44ab-8731-24658ff6f08f">

If applicable, add screenshots to help explain the bug.

Create boot disk process automatically stops:
<img width="987" alt="image" src="https://github.com/user-attachments/assets/cbb7c7cc-fd76-442d-a92d-1976b51c3573">

**Comment by ninxsoft** [comment]
@A00736470 thanks for raising this issue, it appears to be the same issue as https://github.com/ninxsoft/Mist/issues/138

Good news is, it's a simple fix: https://github.com/ninxsoft/Mist/pull/145
