### ISSUE TITLE
Version ID needed

### ISSUE THREAD

**Issue by Fred-IV** [ninxsoft/Mist#136]
### :bulb: Needs better version identification information of installers list

Mist lists a package as "14.6 (23G80) 2024-07-29 13.68 GB", but macOS lists it only as "19.6.01".

### :white_check_mark: Proposed solution

Is there a way Mist can show us the "19.6.01" in the list?
There's no way to tell what the saved versions on the server are. There is no further info in "File Info" in macOS, so there's no way to know, other than to download it again.

### :adhesive_bandage: Alternatives Solutions + Workarounds

Is there an online list?
I cannot find a way to identify the file version to macOS version.

### :information_source: Additional context

- Would you also like to see this implemented in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x:
- Links to 3rd-party tools / references / documentation
- Screenshots / diagrams that help explain the feature request

**Comment by wakco** [comment]
Mist lists the macOS version that gets installed by the package, it has never listed the package version.

**Comment by ninxsoft** [comment]
@Fred-IV unfortunately to my knowledge, Apple does not provide the installer app bundle versions online without having to download the installers themselves.

Will close this issue for now but more than happy to re-open if this changes in the future 👍
