### ISSUE TITLE
Download High Sierra 10.13.6 (17G66) only got a ~500MB installer

### ISSUE THREAD

**Issue by hronro** [ninxsoft/Mist#138]
Download High Sierra 10.13.6 (17G66) only got a ~500MB installer, which is obviously too small.

**Comment by weegie247** [comment]
Just to add on to my previous comment, rather than editing it, it does seem that the Sierra process is a lot longer and seems to have completed the process so I think there must be an issue with the status of the installer Mist pulls in for High Sierra.

**Comment by gjoris** [comment]
+1, having the same issue. 

The bootable USB also cannot be used - upon starting the install, the Mac OS X installer says the installer is damaged and can't be used.

**Comment by EAZYBLACK** [comment]
+1 same issue

**Comment by tifredfr** [comment]
Hi,

+1 same issue :)

**Comment by clickoncentral** [comment]
+1 same issue


*Thank you.*


*Please be aware that this communication is intended only for the recipient
and may contain confidential and legally privileged information. The views
expressed in this email are solely those of the author and do not
necessarily represent those of Click On Central. Any unauthorised review,
retransmission, dissemination, reliance on, or other use of this
communication is strictly prohibited. If you have received this email in
error, please notify Click On Central immediately by returning the email
and deleting all copies from your system.*

**Comment by dordal** [comment]
... and another +1. Only a 500MB installer for High Sierra

**Comment by ninxsoft** [comment]
Okay so I was able to replicate the issue - oddly enough when attempting to create the **macOS High Sierra** Installer in a temporary disk image, a portion of it still ends up in `/Applications/Install macOS High Sierra.app`.

https://github.com/ninxsoft/Mist/pull/144 adds the workaround which merges the contents all together into a single **~5.23GB** installer 👍
