### ISSUE TITLE
Create install media without download

### ISSUE THREAD

**Issue by handarbyte** [ninxsoft/Mist#139]
### :bulb: Description

Creating install media should be (additonally) possible without download, but with previously downloaded installers.

### :white_check_mark: Proposed solution

A button to choose an installer file within the dialog of preparing the creation of the install media.

### :adhesive_bandage: Alternatives Solutions + Workarounds

A way to copy already downloaded installers into cache directory.

**Comment by ninxsoft** [comment]
@handarbyte Mist supports caching of macOS Installers, so you don't have to re-download everything you need to create an installer / disk image / package / USB installer.

You can enable **Cache downloads** via the app settings:

![Installers](https://github.com/user-attachments/assets/fd91a376-5615-418a-b89e-e79c427d7f92)

So when you go to create a bootable installer, it will just load from the cache 👍
