### ISSUE TITLE
Alternate temp file location

### ISSUE THREAD

**Issue by jaknz** [ninxsoft/Mist#14]
Rather than quitting with an error message when the startup volume doesn't have enough free space, would it be feasible to add a command flag to specify an alternate temp directory for the build? This _might_ be a limitation of the macOS installer process though, in which case it's understandable if this is not possible.

**Comment by ninxsoft** [comment]
My understanding is that there is a current limitation / bug with the macOS Installer packages provided by Apple, in that they are required to be installed on the booted macOS volume (to generate the **Install macOS.app**).

Happy to investigate some options, perhaps better messaging or a way to workaround the Apple bug.

**Comment by ninxsoft** [comment]
Proposing the following changes:
*  Add a `-t | --temporary-directory` option to specify a custom temporary download location
    * Can be on an external volume
    * Defaults to `/private/var/tmp`
*  Continue checking for enough free space on `/` (total size of the macOS Installer packages)
*  Check for enough free space on the `--temporary-directory` volume (total size of the macOS Installer packages)
*  Check for enough free space on the `--output-directory` volume (total size of the macOS Installer packages x each exported type)

This should help with space savings. For the time being the macOS Installer will end up in `/Applications` if built successfully.

Investigating ways to build to a custom location (see #16).

**Comment by ninxsoft** [comment]
Added in 275f635616decd8fc97f589a71c10ca7fef70836 and 2af256a2b3e5c462ae41578fb88c932037ebd49a
