### ISSUE TITLE
Add ability to download iOS IPSW's

### ISSUE THREAD

**Issue by simplytoast1** [ninxsoft/Mist#140]
### :bulb: Description

It would be fantastic to be able to download iOS, iPadOS as homeOS IPSW's for configuration via Apple Configurator.

### :white_check_mark: Proposed solution

Add an IPSW tab to allow the download of IPSW files.

### :adhesive_bandage: Alternatives Solutions + Workarounds

Use an alternative website

### :information_source: Additional context

- Would you also like to see this implemented in [mist-cli](https://github.com/ninxsoft/mist-cli)?  :x:
- Links to 3rd-party tools / references / documentation
- Screenshots / diagrams that help explain the feature request

**Comment by Stefanmargaroli** [comment]
What would be even cooler is a response on how to get mist to work✌🏼

Sent from my iphone, short but not meant to be impolite

Op 17 sep. 2024 om 05:05 heeft simplytoast1 ***@***.***> het volgende geschreven:

﻿

💡 Description

It would be fantastic to be able to download iOS, iPadOS as homeOS IPSW's for configuration via Apple Configurator.

✅ Proposed solution

Add an IPSW tab to allow the download of IPSW files.

🩹 Alternatives Solutions + Workarounds

Use an alternative website

ℹ️ Additional context

  *   Would you also like to see this implemented in mist-cli<https://github.com/ninxsoft/mist-cli>? ❌
  *   Links to 3rd-party tools / references / documentation
  *   Screenshots / diagrams that help explain the feature request

**Comment by ninxsoft** [comment]
@simplytoast1 great feature request however I do believe it would complicate the purpose of the Mist app, which is specific to macOS.

That being said, I do have plans to create a separate IPSW-only download tool (no macOS installers) - so stay tuned!

**Comment by luckman212** [comment]
@ninxsoft The ability to also download IPSW files for macOS would be useful as well for creating VMs e.g. with UTM.

**Comment by ninxsoft** [comment]
@luckman212 Mist does support downloading macOS IPSWs 👍

**Comment by luckman212** [comment]
Ah I see that Mist CLI can list the IPSW information, but I'm sorry I didn't see anywhere to do it in the GUI app @ninxsoft 

Is that you meant?
