### ISSUE TITLE
The file “InstallAssistant.pkg.integrityDataV1” couldn’t be opened.

### ISSUE THREAD

**Issue by zeromake** [ninxsoft/Mist#143]
### :beetle: Description

on `Download InstallInfo.plist` network error, reopen on `Verify InstallAssistant.pkg` has The file “InstallAssistant.pkg.integrityDataV1” couldn’t be opened.

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
2. Click on `Installers` -> `macOS Sequoia`
3. Retrying multiple times has been this error

### :white_check_mark: Expected Behaviour

Automatically remediate errors where the file does not exist

### :computer: Environment

- Mist version: 0.20
- macOS Version: **Sonoma 14.5**

### :camera: Screenshots

<img width="480" alt="截屏2024-10-01 00 44 20" src="https://github.com/user-attachments/assets/835912b4-1990-4003-a6f3-1d6ad3efd271">

### :information_source: Additional context

Is there any way to get rid of all the data of the application first?

**Comment by zeromake** [comment]
It's not a software issue, it's my network issue

**Comment by Stefanmargaroli** [comment]
Why do I keep getting emails of other people’s issues but mine where never logged or addressed?

Sent from my iphone, short but not meant to be impolite

Op 2 okt. 2024 om 11:11 heeft zeromake ***@***.***> het volgende geschreven:

﻿

Closed #143<https://github.com/ninxsoft/Mist/issues/143> as completed.
