### ISSUE TITLE
Why is this a .pkg installer instead of an .app? 

### ISSUE THREAD

**Issue by vordenken** [ninxsoft/Mist#2]
Is there any technical reason for this? 

I myself like normal apps (the ones you have to drop into the programs folder) way more because it makes the app look "lighter"? I don't know how to describe it but maybe you know what I mean. Also things with an installer often can't be (fully) removed by dragging the app into the bin which adds confusion to it. 

Other than that great app and keep it up!

**Comment by ninxsoft** [comment]
Hi @vordenken, the releases are currently only available as macOS Installer packages as the **Privileged Helper Tool** is placed in `/Library/PrivilegedHelperTools/com.ninxsoft.mist.helper` during installation.

Can definitely make Mist.app available as a Disk Image (DMG) release asset, but this will require the user to enter their password when running Mist to install / update the Privileged Helper Tool.

**Note:** You can observe this behaviour by manually deleting `/Library/PrivilegedHelperTools/com.ninxsoft.mist.helper` and trying to downloading something via Mist - you will be prompted to install the Privileged Helper Tool.

**Comment by vordenken** [comment]
Hi @ninxsoft, thanks for the quick and helpful reply. 
Maybe the Mist.app as an option besides the .pkg would be nice or even make it obvious in the gui the first time its opened. 

If I drag the application in the bin the helper tool will not get deleted then, right? Are there any plans to add an uninstaller of some sort to remove all of the application and its helper tool?

**Comment by ninxsoft** [comment]
Will definitely look into a DMG option, where the Privileged Helper Tool can be installed on first launch / first download.

Regarding moving the app to the Bin, correct, the helper tool + LaunchDaemon will not be removed. I can whip up an uninstall script to perform all cleanup steps 👍

**Comment by ninxsoft** [comment]
@vordenken I have added an uninstall script here: [Link](https://github.com/ninxsoft/Mist/blob/main/Scripts/uninstall.sh)

This will unload the Privileged Helper Tool, as well as remove the LaunchDaemon, Privileged Helper Tool and Application 👍

Regarding the DMG installer, I will look at exporting this for the next version of Mist.

Thanks!
