### ISSUE TITLE
receiving "Invalid type in JSON" error when running mist

### ISSUE THREAD

**Issue by Coros** [ninxsoft/Mist#20]
I haven't used mist since the 11.5.1 release.  I'm attempting to get 11.5.2 and receiving this error:

mist --list
┌────────┐
│ SEARCH │
└────────┘
  ├─ Searching for macOS versions...
  ├─ Searching Standard catalog...
2021-08-11 14:06:37.753 mist[10233:2250981] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__NSTaggedDate)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff205ec83b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20324d92 objc_exception_throw + 48
	2   Foundation                          0x00007fff21352561 _writeJSONValue + 216
	3   Foundation                          0x00007fff2135301f ___writeJSONObject_block_invoke + 347
	4   libswiftCore.dylib                  0x00007fff2cae9211 $ss26_SwiftDeferredNSDictionaryC23enumerateKeysAndObjects7options5usingySi_ys9UnmanagedVyyXlG_AHSpys5UInt8VGtXBtFTf4dnn_n + 337
	5   libswiftCore.dylib                  0x00007fff2c8d4e45 $ss26_SwiftDeferredNSDictionaryC23enumerateKeysAndObjects7options5usingySi_ys9UnmanagedVyyXlG_AHSpys5UInt8VGtXBtFTo + 37
	6   Foundation                          0x00007fff21352972 _writeJSONObject + 486
	7   Foundation                          0x00007fff214fd558 -[_NSJSONWriter dataWithRootObject:options:] + 71
	8   Foundation                          0x00007fff2135236d +[NSJSONSerialization dataWithJSONObject:options:error:] + 117
	9   mist                                0x000000010ff8f668 mist + 128616
	10  mist                                0x000000010ff90648 mist + 132680
	11  mist                                0x000000010ff7f104 mist + 61700
	12  mist                                0x000000010ff82099 mist + 73881
	13  mist                                0x000000010ff82b89 mist + 76681
	14  mist                                0x000000011003791e mist + 817438
	15  mist                                0x000000010ff74c8e mist + 19598
	16  libdyld.dylib                       0x00007fff20494f3d start + 1
	17  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by ninxsoft** [comment]
Looks like the `DeferredSUEnablementDate` date value within each dictionary of the SUCatalog is causing the issue.

Removing this key before proceeding fixes this issue.

PR incoming 👍
