### ISSUE TITLE
Disable Tabs (since opening multiple tabs/windows can cause download conflicts)

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#23]
In the View menu of Mist, you can Show Tab Bar and add another Mist window tab (which can even be dragged out to be another Mist window). This allows you to start multiple downloads simultaneously, but the underlying code doesn't account for this and the multiple downloads conflict with each other and the first one will end up failing and then both progress displays actually show progress for just the download that was started last.

I could show more detail here with screenshots if needed, but it's pretty easy to replicate and pretty easy to avoid the issue by just disabling tabs from being able to be opened so that there is only ever a single Mist tab/window and only one download can be done at a time.

**Comment by ninxsoft** [comment]
Nice pickup @PicoMitchell!

And boom, one-line fix: 8f47603af3bce79fb6bbb1cfb253d36a74394d6b
