### ISSUE TITLE
Empty Cache button should be enabled when cache has contents even if Cache Downloads is not enabled

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#25]
It is possible for the Cache folder to have some cached data from a canceled download. But, if the "Cache downloads" checkbox is not enabled then the "Empty Cache…" button is also not enabled.

In this case I think it would make sense for the "Empty Cache…" button to be enabled if the cache has any contents regardless of whether or not the the "Cache downloads" checkbox is enabled.

**Comment by ninxsoft** [comment]
Another tiny fix: https://github.com/ninxsoft/Mist/commit/33a866ef0f0f34ee3298e0102b93f5e6c836bd8a

I recall tossing up between keeping **"Empty Cache..."** being disabled conditionally and what you described above, and seem to have landed on the former. The button will now only be disabled if the cache directory is empty (0 bytes) 👍

![Empty Cache](https://user-images.githubusercontent.com/4812595/206900002-8362d1e4-43e8-4dc6-955f-856cd6002311.png)
