### ISSUE TITLE
On Monterey, the right edge of the download button is cut off.

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#26]
Title says it all, but here's a screenshot as well:
<img width="461" alt="Screen Shot 2022-12-10 at 2 24 50 PM" src="https://user-images.githubusercontent.com/7358089/206877581-e41266f2-8ae9-40b3-9899-585546a8427a.png">

**Comment by ninxsoft** [comment]
Eww gross 😛 I'll see if I can make the default window size slightly bigger 👍

**Comment by ninxsoft** [comment]
Actually, appears to be case on macOS Ventura also:

![Clipping](https://user-images.githubusercontent.com/4812595/206900385-effdb715-3b26-4e31-93ec-10b9579d21bd.png)

Might have something to do with the scrollbar 🤔

**Comment by ninxsoft** [comment]
Yep, padding the trailing side of the button seems to fix it:

![No clipping](https://user-images.githubusercontent.com/4812595/206900481-b55a7c82-d6e4-463a-a8de-0f30f0f9bdd0.png)

**Comment by ninxsoft** [comment]
Fixed with the tiniest amount of padding: https://github.com/ninxsoft/Mist/commit/a6d730acc06a735cb7df55c216fe65e7d5ebdba5
