### ISSUE TITLE
Cache directory permissions error

### ISSUE THREAD

**Issue by ihubgit** [ninxsoft/Mist#28]
Hi trying to get the latest 13.1 installer (application) on my Apple silicon, but i'm getting the following error (unchecked uncompatible versions already) :

Error: You don’t have permission to save the file “012-60271” in the folder “Cache”.

**Comment by ninxsoft** [comment]
Hi @ihubgit, am I able to confirm that you are running **Mist version 0.4**? We recently added a feature that prompts you if your cache folder has incorrect ownership / permissions: https://github.com/ninxsoft/Mist/issues/19

You should be prompted that your cache directory has incorrect ownership / permissions before attempting a download:


![Invalid cache directory](https://user-images.githubusercontent.com/4812595/206411314-82ad6fdd-6778-4d39-bf2f-f319303544e6.png)

**Comment by ninxsoft** [comment]
If you are running an older version of Mist, you can update directly within the app or download from the [releases page](https://github.com/ninxsoft/Mist/releases) 👍

**Comment by ihubgit** [comment]
hi yes, i'm running latest (0.4) and i'm not getting any prompt.

**Comment by ninxsoft** [comment]
I may have missed some weird edge case in my testing 🤔

@ihubgit are you able to provide me with the ownership and permissions of your cache directories?

Assuming you're using the default cache directory, are you able to paste the output of the following:

```bash
ls -al /Users/Shared/Mist
ls -al /Users/Shared/Mist/Cache
```

**Comment by ihubgit** [comment]
ls -al /Users/Shared/Mist/Cache
total 0
drwxr-xr-x   2 root  wheel   64 30 avr  2022 .
drwxrwxrwt  16 root  wheel  512 15 déc 10:41 ..
ls: /Users/Shared/Mist/Cache: No such file or directory

**Comment by ihubgit** [comment]
when i try to download firmware, it starts alright, only the installers are problematic.

**Comment by ninxsoft** [comment]
@ihubgit thanks for the insight, I have found a bug where Mist will raise an error if the Cache folder does not exist when checking for invalid ownership / permissions - this should fix the issue you are having with being able to save to the Cache directory.

Will hopefully have an update out soon, will request some assistance testing once it's out 🙏

**Comment by ninxsoft** [comment]
Commit: 08cf22f07dc7fe9316510cad483b275d842872cc

**Comment by NorseGaud** [comment]
I have this issue too. Excited to see it released :)

**Comment by NorseGaud** [comment]
I have this issue too with the latest release. Even when running Mist.app as root. I can test if needed.

**Comment by ninxsoft** [comment]
@ihubgit + @NorseGaud am I able to confirm if this is still the case when running Mist.app 0.5?

Are you also able to confirm you have allowed Full Disk Access to Mist.app (details in the [README](https://github.com/ninxsoft/Mist/blob/main/README.md)):

![Full Disk Access](https://user-images.githubusercontent.com/4812595/211695540-dc646f81-9a6f-4422-904c-61fae1113f35.png)

Thanks 🙏

**Comment by NorseGaud** [comment]
Yes, happens in 0.5.

**Comment by hereisderek** [comment]
getting this error on version 0.5, but only with cache enabled.
tried setting it to an external exfat drive and a sparsebundle disk mounted drive

**Comment by NorseGaud** [comment]
Still a problem. Can't use the app at all for .app
<img width="917" alt="Screenshot 2023-05-09 at 1 31 31 PM" src="https://github.com/ninxsoft/Mist/assets/5896030/b1e37e4a-a041-470a-9b00-d9290ee4d4ba">

```
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
```

**Comment by ninxsoft** [comment]
I have not been able to replicate the issue with Full Disk Access **disabled**, therefore I have added the following warning message when attempting to build a macOS Installer:

![Full Disk Access](https://github.com/ninxsoft/Mist/assets/4812595/a3a55000-5d8d-4d68-b8bb-aa83170eb366)

Ironically, Mist requires Full Disk Access to read the contents of `/Library/Application Support/com.apple.TCC/TCC.db`, which is used to verify if Mist has Full Disk Access... 🙃

Clicking on **Allow...** takes you to **System Settings** > **Privacy & Security** > **Full Disk Access**

This has been added in https://github.com/ninxsoft/Mist/commit/49eae0e017c062489f93ffac11caeec1a784c717, with the intention to release **version 0.6** with the updates from WWDC next week 👍

**Comment by ninxsoft** [comment]
Mist has been updated to [version 0.6](https://github.com/ninxsoft/Mist/releases/tag/v0.6) - are you able to try with this new version and report back? 🙏

**Comment by hereisderek** [comment]
i found that the error is easier to reproduce on a different file system, e.g. an external harddrive formatted as exFAT, not sure if you could create a sparsedbundle with apfs fs on that exfat drive

**Comment by NorseGaud** [comment]
Hey! Deleting `/Users/Shared/Mist` worked!!! Wohooo
