### ISSUE TITLE
Feature Request: Reveal in Finder button on the completion screen

### ISSUE THREAD

**Issue by BigMacAdmin** [ninxsoft/Mist#32]
It would be nice if the "completion" window had a "Show in Finder" or "Reveal in Finder" button that would open finder to that file, with the file selected.

![Screenshot 2023-01-12 at 9 57 49 AM](https://user-images.githubusercontent.com/106293503/212143593-436781de-368b-4498-ab35-a37e946fde30.png)

**Comment by ninxsoft** [comment]
You can turn on Notifications in the app settings, which will alert you once a download has completed:

![Settings](https://user-images.githubusercontent.com/4812595/212211501-a3446bcb-4bda-4544-a03b-20a5fe79b69b.png)

Clicking on **Show** in the notification will open the parent folder in Finder:

![Notifications](https://user-images.githubusercontent.com/4812595/212223995-0aa3fc21-eeb1-4370-9a1e-d984bcd941de.png)

This does, however, only show if Mist is **not** the frontmost / active app.

Perhaps I can add another checkbox in the app settings to "Show in Finder" upon download completion? 🤔

**Comment by ninxsoft** [comment]
@BigMacAdmin you have twisted my arm 😆

![Show In Finder](https://user-images.githubusercontent.com/4812595/232288029-49d73e52-207a-459a-82bb-e1e0ab1e6c1d.png)

Pull Request is on it's way!

**Comment by ninxsoft** [comment]
Make that just a commit: https://github.com/ninxsoft/Mist/commit/0392412d3e765a11b57b09fbe44a1193f98c9292
