### ISSUE TITLE
Firmware vs. Installers

### ISSUE THREAD

**Issue by mrzool** [ninxsoft/Mist#33]
Thanks for this great tool.

I'm not super clear about the distinction between firmwares and installers. By reading the README I understand that firmwares are for Apple Silicon while installers are for Intel Macs? Or am I missing something?

Sorry for the noob question.

**Comment by kevinmcox** [comment]
The firmware files (.IPSW) can be used to completely wipe and reinstall macOS (and hardware firmware) on Apple Silicon computers in under 10 minutes using Apple Configurator: https://support.apple.com/guide/apple-configurator-mac/revive-or-restore-a-mac-with-apple-silicon-apdd5f3c75ad/mac

**Comment by mrzool** [comment]
Wow, I had no idea! 🤯

Thanks!
