### ISSUE TITLE
what the difference between Firmwares and Installers

### ISSUE THREAD

**Issue by Y0usefmahdi** [ninxsoft/Mist#34]
what the difference between Firmwares and Installers
i want to format my m1 macbook via USB should i use the Firmwares or the Installers

note: i didn't have another macbook so i should do it via USB only

**Comment by ninxsoft** [comment]
Hi @Y0usefmahdi, Firmwares can be used to restore Apple Silicon Macs where Installers generally used on Intel Macs (newer versions of Installers support both Apple Silicon and Intel Macs).

You can see brief descriptions of both in the app settings:

![Screenshot 2023-01-31 at 9 55 43 pm](https://user-images.githubusercontent.com/4812595/215741522-f41f0122-fc8d-4733-b071-58e7ec07d2fb.png)

![Screenshot 2023-01-31 at 9 55 45 pm](https://user-images.githubusercontent.com/4812595/215741547-6ae8b917-29e5-4974-a2ec-567422d5561d.png)

If you are planning on formatting your Apple Silicon Mac, you can reinstall macOS without Mist - see: [How to reinstall macOS](https://support.apple.com/HT204904)

If you want to restore a specific version of macOS, after downloading the firmware my understanding is you will require another Apple Silicon Mac running [Apple Configurator](https://support.apple.com/apple-configurator) to perform the restore.
