### ISSUE TITLE
Request: Self Update Checking

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#36]
While it's not normal for command line tools to auto-update themselves, I think having an update check could be a convenient thing to add to the `version` output, and/or to check for updates on every non-quiet load and include a note in the verbose output if an update is available.

**Comment by ninxsoft** [comment]
Generally speaking, command line tools don't self-update, and package managers like [Homebrew](https://brew.sh) (#19) make it a point to [call this out](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-tools-that-upgrade-themselves).

Having said that, I do like the idea of a quick check (on launch / `mist version`) to see if you are running the latest version.

**Comment by ninxsoft** [comment]
Perhaps the following:

```bash
# current
➜ ~ mist version
1.5 (latest: 1.5)

# out-of-date
➜ ~ mist version
1.5 (latest: 1.6)
Visit https://github.com/ninxsoft/mist to grab the latest release of mist
```

**Comment by PicoMitchell** [comment]
I've started taking advantage of `exit` in `awk` when I only want the first line to avoid having to call a second command like `head` so just `awk`ing the current version could be even easier: `mist version | awk '{ print $1; exit }'`
