### ISSUE TITLE
Signed package

### ISSUE THREAD

**Issue by Moulick** [ninxsoft/Mist#36]
I was attempting to submit Mist as a cask in homebrew, which requires that packages be signed. Is it possible for the `Mist.0.5.pkg` to be signed? Also, I think macOS on ARM requires applications to be signed.

**Comment by Moulick** [comment]
https://github.com/Homebrew/homebrew-cask/pull/141504

**Comment by ninxsoft** [comment]
The Mist packages and apps are already signed and notarized when uploaded to GitHub:

```bash
pkgutil --check-signature Mist.0.5.pkg 
Package "Mist.0.5.pkg":
   Status: signed by a developer certificate issued by Apple for distribution
   Notarization: trusted by the Apple notary service
   Signed with a trusted timestamp on: 2022-12-29 06:10:33 +0000
   Certificate Chain:
    1. Developer ID Installer: Nindi Gill (7K3HVCLV7Z)
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           66 9A 5B 80 72 F8 40 29 EF C0 B8 22 ED A9 D2 7B 21 62 05 E3 BE 76 
           32 1B AC 26 7D 6E F4 D9 4D 70
       ------------------------------------------------------------------------
    2. Developer ID Certification Authority
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
           F2 9C 88 CF B0 B1 BA 63 58 7F
       ------------------------------------------------------------------------
    3. Apple Root CA
       Expires: 2035-02-09 21:40:36 +0000
       SHA256 Fingerprint:
           B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
           68 C5 BE 91 B5 A1 10 01 F0 24
```

```bash
spctl -a -vv Mist.app 
Mist.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Nindi Gill (7K3HVCLV7Z)
```

I see https://github.com/Homebrew/homebrew-cask/pull/141504 was merged - is the cask working as expected?

**Comment by Moulick** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15780903/224485909-64e0fe5b-11e7-49ef-8628-35733a980f10.png">

Sorry, my bad. The pkg is indeed signed correctly. I didn't look too closely at the `brew audit` output. Brew audit output is misleading in claiming the package is unsigned and "Please contact the upstream developer to let them know they should notarize their package." as you can see in the screenshot.

It seems the minimal installation of Xcode does not support signature checking and requires the full Xcode 🙄
