### ISSUE TITLE
Request: On Demand Self Updating

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#37]
As a possible future extension of https://github.com/ninxsoft/Mist/issues/36, it could also be nice and convenient to have an on demand self updating option, such as `mist update` (not automatic updating since that's not typical for command line tools). If of course you feel that it would fit into the Mist command line options and functionality.

**Comment by ninxsoft** [comment]
I have long-term plans to convert `mist` into a SwiftUI app, and have looked into the [Sparkle](https://sparkle-project.org) framework for auto-updates.

What this looks like for the command line component is yet to be determined.

Keeping this issue open so we can circle back 👍.

**Comment by PicoMitchell** [comment]
Another user convenience idea that is not quite auto-updating, but makes updating easier for the user...

In my own `mkuser` script I added an `online` parameter to the `--version` option for the user to be able to quickly open the Releases page on GitHub in the default browser when an update is available: https://github.com/freegeek-pdx/mkuser#--version--v--online--no-parameter-

**Comment by ninxsoft** [comment]
I feel this has been solved indirectly via `brew install mist` / `brew upgrade mist`, I just need to better document these steps, and be more proactive with updating the brew formula.

Closing this issue as any SwiftUI-related work will warrant a separate issue.
