### ISSUE TITLE
RFE: iso images dynamic size instead of fixed size

### ISSUE THREAD

**Issue by devZer0** [ninxsoft/Mist#37]
hello, 

thanks for making this cool tool !

all iso images seem to be created with 15,57 GB in size, which is particularly larger what is needed. 

that is wasting a lot of space and time for copying those

could iso size be automatically be adjusted to fit the pkg size ?

**Comment by ninxsoft** [comment]
Thanks for using Mist!

The current (crude) method for calculating sizes is as follows:

https://github.com/ninxsoft/Mist/blob/07e698d953c362abffe826e5de572adc1f9c84c1/Mist/Model/Installer.swift#L265-L273

- The (package) size is just a sum of all individual sizes that Apple provides
- The DMG size is the total package size rounded up to the nearest gigabyte + 1.5 GB
- The ISO size is the total package size rounded up to the nearest gigabyte + 1.5 GB

The increase in size was introduced over in https://github.com/ninxsoft/mist-cli/issues/102

I might do some testing to see if I can come up with a smarter formula (I want to avoid the user having to specify if possible).

Open to suggestions!

**Comment by carlashley** [comment]
You _might_ be able to create a `sparseimage` and then mount it, do all the operations required with the mounted sparse image volume as the target, unmount it, then convert the `.sparseimage` to relevant ISO or DMG format as needed; that should give you an ISO/DMG file that only consumes the require amount of space.

**Comment by ninxsoft** [comment]
Building upon the suggestion from @carlashley, I have been able to shrink down the ISOs dynamically by building a resized DMG based off the bootable DMG before it gets converted to an ISO:

| **Release** | **ISO Size** | **Free Space (when mounted)** |
| :- | :-: | :-: |
| macOS Monterey 12.6.7 (21G651) | 14.3 GB | ~300 MB |
| macOS Ventura 13.4.1 (22F82) | 13.7 GB | ~300 MB |

This is much better than the 1-2 GB of free space that was not required 👍
