### ISSUE TITLE
not able to boot from ISO images created with MIST

### ISSUE THREAD

**Issue by devZer0** [ninxsoft/Mist#38]
hello, 

i created iso images for ventura and monterey on ventura m1  and 2018/intel macbook pro, but i cannot boot from those. 

the ventura icon is shown in boot menu when option/alt is pressed for boot media selection, but after selecting it does not boot. 

boot is skipped and the macbook boots in recovery mode from disk, if there i s installation on disk. otherwise error message is shown that system can't boot

i use the iso images with iodd cdrom emulator and never had any problem with any iso there and i'm using that device a LOT, 

so i assume there is something broken with the ISOs

**Comment by ninxsoft** [comment]
Hi @devZer0, are you able to please verify an ISO boots correctly by building one following the steps outlined here:

https://geekbullet.com/download-and-create-macos-ventura-iso-file/

This should help rule out if the issue is specific to Mist 🙏

**Comment by ninxsoft** [comment]
@devZer0 just following up if you are still having issues booting from the ISOs created via Mist?

**Comment by AlexKorovyansky** [comment]
I'm experiencing a similar problem. I'm using VirtualBox and trying to create VM with OS X Ventura on OS X host.

Host: MacBook Pro 16-inch, 2019 (C02D40PFMD6T), Ventura 13.1.1
Target VM: Ventura 13.1.1

I've tried both Mist and steps that described on geekbullet. Everything is good at ISO and VM creation stages. But it fails right after VM start. I made a screenshot this the displayed errors. Hope you can give some advice how to make it working.

Thanks!

<img width="521" alt="Screenshot 2023-05-17 at 11 08 20 PM" src="https://github.com/ninxsoft/Mist/assets/479961/bf018028-6ce5-46f9-9946-ee41e0cccdf3">

**Comment by ninxsoft** [comment]
Unfortunately the VirtualBox docs don't give much insight into what Mac operating systems are supported:

https://docs.oracle.com/en/virtualization/virtualbox/7.0/user/BasicConcepts.html#intro-macosxguests

With the shift to Apple Silicon hardware + the tightening of security of each new release of macOS, I feel less confident that ISOs can be used to successfully boot and install macOS on modern hardware.

That being said, I was able to get macOS Ventura booting correctly in Parallels Desktop (albeit on Apple Silicon hardware via an IPSW restore):

https://kb.parallels.com/125561/

<img width="1132" alt="Parallels Desktop" src="https://github.com/ninxsoft/Mist/assets/4812595/06f4520b-1b19-49e0-a0ab-66063bb5f019">

I'll keep this issue open for a tiny bit longer but on the surface it appears this may be more difficult than expected via VirtualBox + I do not have access to test on Intel hardware I'm afraid
