### ISSUE TITLE
homebrew cask?

### ISSUE THREAD

**Issue by JounQin** [ninxsoft/Mist#4]

**Comment by ninxsoft** [comment]
Hi @JounQin, I am reluctant to create a Homebrew cask as Mist has it's own built-in updater (via [Sparkle](https://github.com/sparkle-project/Sparkle)) and I anticipate issues with Homebrew's updating / version mechanism.

**Comment by hisaac** [comment]
FYI, Homebrew does have the ability to define a Cask as auto-updating, which means Homebrew will allow the app to manage updating itself. It installs the newest version when you run `brew install <app_name>`, but then doesn't install updates to the app when running `brew upgrade`.

<img width="639" alt="Screenshot 2022-12-07 at 11 50 16 AM" src="https://user-images.githubusercontent.com/923876/206257369-d8dcdff8-e445-4b5c-9414-78ecd8fda2d8.png">

From here: https://docs.brew.sh/Cask-Cookbook#optional-stanzas

I agree with @JounQin that it'd be nice to have this as a Cask. That's the primary way I install apps these days. :)
