### ISSUE TITLE
Mist thinks 11.6.1 RC is a production release.

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#40]
Because of how Mist uses a default catalog url that includes betas (which is awesome in general!), it is mistaking the 11.6.1 RC for a production release when running a command like `mist download --image 'Big Sur'` since it is it not marked as a beta in its name in the list.

Not sure about the best approach to solving this since I think it's generally convenient to list betas by default, but maybe Mist should add the catalog/seed source name as a column and have some simple way to only download Big Sur from the production catalog within a command?

I see there is already a way to pass a specific catalog url, but that feels overly cumbersome vs being able to choose the catalog by name such as Production vs Developer (the way that MDS makes this switching catalog sources convenient).

<img width="602" alt="mist-11 6 1-rc" src="https://user-images.githubusercontent.com/7358089/137566540-ab5d13c3-7439-4dd6-b32a-fd47ad5f27c1.png">

**Comment by ninxsoft** [comment]
Thanks @PicoMitchell for looking into this!

I like the idea of having a `-b` / `--include-betas` flag (set to `false` by default), which will help separate out non-beta releases.

I also have some over-complicated logic for the catalog URLs, I am in favour of replacing the current logic with the following hardcoded values:

**standard**: https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
**customer**: https://swscan.apple.com/content/catalogs/others/index-12customerseed-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
**developer**: https://swscan.apple.com/content/catalogs/others/index-12seed-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
**public**: https://swscan.apple.com/content/catalogs/others/index-12beta-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz

**Comment by PicoMitchell** [comment]
Thank you! Looking forward to playing with this update tomorrow!
