### ISSUE TITLE
Should Still Show Current Version Without Internet

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#42]
Just playing with new features in Mint 1.6 and noticed that the current version is not shown with `mist version` when the internet is not available:

With internet:
```
pico@Computer ~ % mist version  
1.6 (latest: 1.6)
```

Without internet:
```
pico@Computer ~ % mist version
Unable to check for latest version.
```

**Comment by ninxsoft** [comment]
Pull request incoming - nice pickup!
