### ISSUE TITLE
13.3.1 installer is actually downloading 13.3 build 22E252

### ISSUE THREAD

**Issue by mrmte** [ninxsoft/Mist#43]
When clicking on downloading the 13.3.1 installer i can see with suspicious package it has actually downloaded 13.3 build 22E252

**Comment by ninxsoft** [comment]
@mrmte am I able to confirm that you are using Suspicious Package to verify a macOS Installer Package (.pkg) that you are downloading and exporting from Mist?

When downloading **macOS Ventura 13.3.1 (22E261)** via Mist and exporting as a package, this is what I am seeing:

![Install macOS Ventura 13 3 1_22E261](https://user-images.githubusercontent.com/4812595/233768499-2a34d1d4-852f-46d3-a9fe-7e171f3cd452.png)

Are you using the QuickLook plugin (space bar) by any chance? Or loading the package direction in the Suspicious Package app? In my experience the quicklook plugin can sometimes take a little time to refresh. Here is what I see:

![QuickLook](https://user-images.githubusercontent.com/4812595/233768540-3db1f810-3099-433e-8a56-8c161e94110f.png)

**Comment by mrmte** [comment]
I don’t know what you are saying if you look inside the pkg at the version plsit has downloaded 13.3 not 13.3.1 build Can confirm this is the same with the command line mist and other tools to download the pkg so it may actually be an issue on Apples end where someone has made a mistake.

**Comment by mrmte** [comment]
closing i have confirmed it is an issue in the info plist by Apple and they are looking at it. It is not a problem with the tool. Workaround i am using is to reference instead the CFBundleShortVersionString of the installer app.
