### ISSUE TITLE
Fails to download 10.13.6 with "Invalid Termination Status: 1"

### ISSUE THREAD

**Issue by IronCraftMan** [ninxsoft/Mist#44]
When trying to download 10.13.6 as either dmg or app, it fails with "An error has occurred! Invalid Termination Status: 1"

This appears to happen "Create macOS installer in Disk Image" portion of the process. I could not find any logs associated with mist, so I don't know any other information. The disk image does appear to be created and mounted, though.

![Screen Shot 2023-04-23 at 4 58 24 PM](https://user-images.githubusercontent.com/6383303/233873974-9302dd63-bf4c-4e34-a4cb-a00dd61681b8.png)

**Comment by ninxsoft** [comment]
@IronCraftMan thanks for bringing this to my attention!

I seem to be displaying just the `standard error` of a failing command, where I should also be displaying the `standard output` (if present).

For example, this would be more descriptive (ignore the actual error, it's just an example):

![Error](https://github.com/ninxsoft/Mist/assets/4812595/48a70372-99c7-43e0-b9bc-1e6f18c1454c)

I am in the process of preparing an update to Mist (version `0.6`), so I'll circle back and request you to try again if you are still having the issue by then.

Thanks 🙌

**Comment by ninxsoft** [comment]
Mist has been updated to [version 0.6](https://github.com/ninxsoft/Mist/releases/tag/v0.6) - are you able to try with this new version and report back? 🙏

**Comment by IronCraftMan** [comment]
It does appear to be fixed, thanks. But now when trying to download any Firmware, it claims that it requires full disk access. However I already have full disk access enabled in System Preferences.

**Comment by ninxsoft** [comment]
This looks like a known issue relating to how Full Disk Access is being determined - a fix is on the way!

Will keep this issue open until the Full Disk Access bug is resolved 👍

**Comment by ninxsoft** [comment]
Fixed in: https://github.com/ninxsoft/Mist/commit/46bf6206ff947a9e93f1235f7b709c0e104e8546

**Comment by ninxsoft** [comment]
Closing this issue as version 0.7.1 has been released 👍
