### ISSUE TITLE
[Bug] App crashs all time on (Invalid Termination Status '1': hdiutil: attach failed - no mountable file systems)

### ISSUE THREAD

**Issue by ThePredators** [ninxsoft/Mist#45]
Hello,

Everything was working fine then today tried to download an installer for macOS 12.6.6 but the mist app crash all time on the same error. 

I cleaned the cash folder, my mac cash folder as well, removed and reinstalled the app nothing changes on my side :/ 

Here is the issue : 

<img width="516" alt="Screenshot 2023-05-23 at 17 56 13" src="https://github.com/ninxsoft/Mist/assets/20244800/66027037-b385-45d2-bc97-e2399bc3cb09">

**Comment by ninxsoft** [comment]
@ThePredators thanks for bringing this to my attention 🙌

A quick Google search indicates the `hdiutil: attach failed - no mountable file systems` error might be related to a corrupted download? You mentioned that clearing the cache directory did not resolve the issue 🤔 what about when you do not use the cache? You can uncheck this option in the app settings:

![App Settings](https://github.com/ninxsoft/Mist/assets/4812595/6f7cf9c0-2126-4df4-8dbc-e7aeae2631f5)


**Just to rule out any strange behaviour with Disk Images:** Are you able to confirm there no additional mounted volumes via [Disk Utility](https://support.apple.com/en-us/guide/disk-utility/welcome/mac)?

Also might be worth performing a quick reboot of your Mac and trying again 👍

**Comment by ninxsoft** [comment]
Mist has been updated to [version 0.6](https://github.com/ninxsoft/Mist/releases/tag/v0.6) - are you able to try with this new version and report back? 🙏

**Comment by ninxsoft** [comment]
Mist has been updated to [version 0.7.1](https://github.com/ninxsoft/Mist/releases/tag/v0.7.1) - are you able to try with this new version and report back? 🙏

**Comment by ThePredators** [comment]
Hello sorry @ninxsoft  i couldn't answer earlier. 

I fixed my issue using [mist-cli](https://github.com/ninxsoft/mist-cli) which works better.

**Comment by ThePredators** [comment]
> @ThePredators thanks for bringing this to my attention 🙌
> 
> A quick Google search indicates the `hdiutil: attach failed - no mountable file systems` error might be related to a corrupted download? You mentioned that clearing the cache directory did not resolve the issue 🤔 what about when you do not use the cache? You can uncheck this option in the app settings:
> 
> ![App Settings](https://user-images.githubusercontent.com/4812595/240519678-6f7cf9c0-2126-4df4-8dbc-e7aeae2631f5.png)
> 
> **Just to rule out any strange behaviour with Disk Images:** Are you able to confirm there no additional mounted volumes via [Disk Utility](https://support.apple.com/en-us/guide/disk-utility/welcome/mac)?
> 
> Also might be worth performing a quick reboot of your Mac and trying again 👍

Hello sorry @ninxsoft  i couldn't answer earlier. 

i deleted the App using CleanMyMac so that no residual thing are left behind. I also restarted my Mac and also disabled cache but nothing worked for me.

I finally fixed my issue when switching to [mist-cli](https://github.com/ninxsoft/mist-cli) which works better.
