### ISSUE TITLE
Yosemite, El Capitan, and Sierra not downloading

### ISSUE THREAD

**Issue by BenFRC5147** [ninxsoft/Mist#47]
### :beetle: Description

Yosemite, El Capitan, Sierra not working

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
2. Go to 'Installers'
3. Attempt to download 'OS X Yosemite 10.10.5', 'OS X El Capitan 10.11.6', or 'macOS Sierra 10.12.6'
4. The download fails with reason 'Invalid download resume data'

### :white_check_mark: Expected Behaviour

Mist downloads the OS 

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): 0.6
- macOS Version (`sw_vers`): 22F66
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: 13 inch, 2019 Macbook Pro, 4 Thunderbolt 3 ports
  - Chip : 2.4 ghz Quad core i5

### Additional Info

I also noticed, the new legacy OSes dont trip the 'Non compatible OS' warning

**Comment by AKERDoc** [comment]
I am using a 2019 MBP using MacOS 13.4 and I have the same error when downloading OS X El Capitan 10.11.6

**Comment by ninxsoft** [comment]
I am currently unable to replicate this issue - download resume data refers to Mist saving metadata to a temporary location on disk in the event of a connectivity issue (ie. network dropout), with the hope to resume the download at the specified retry values:

![Retry](https://github.com/ninxsoft/Mist/assets/4812595/630fd1b2-db81-4628-8b7a-0da43952f77d)

- Are you able to confirm if you had any network issues when attempting to download these legacy operating systems?
- Does the issue occur consistently? Are you able to replicate it relatively easily? If so, it might help to capture a screen recording so I can better understand the behaviour 🙏
- Legacy operating systems are just 1 x disk image download under the hood. Can you confirm these files download without any issue (from [How to download macOS](https://support.apple.com/en-us/HT211683)):
  - [Sierra 10.12](http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg)
  - [El Capitan 10.11](http://updates-http.cdn-apple.com/2019/cert/061-41424-20191024-218af9ec-cf50-4516-9011-228c78eda3d2/InstallMacOSX.dmg)
  - [Yosemite 10.10](http://updates-http.cdn-apple.com/2019/cert/061-41343-20191023-02465f92-3ab5-4c92-bfe2-b725447a070d/InstallMacOSX.dmg)
  - [Mountain Lion 10.8](https://updates.cdn-apple.com/2021/macos/031-0627-20210614-90D11F33-1A65-42DD-BBEA-E1D9F43A6B3F/InstallMacOSX.dmg)
  - [Lion 10.7](https://updates.cdn-apple.com/2021/macos/041-7683-20210614-E610947E-C7CE-46EB-8860-D26D71F0D3EA/InstallMacOSX.dmg)

**Comment by ninxsoft** [comment]
Re: Compatibility on Intel Macs for the legacy operating systems, this has been updated in https://github.com/ninxsoft/Mist/commit/d44f185e5d2a235fc61bd870a18665933eedfee3 👍

**Comment by BenFRC5147** [comment]
The error occurs consistently for me, I can download using the links from Apple's site directly no problem

https://youtu.be/Er8u6iR83bY

**Comment by AKERDoc** [comment]
I am not a computer expert by far. When you mention capturing a screen recording, what do you mean? Just a screen shot of the error message? I am fairly sure I am not having any network problems with problem downloading other thinks. I am able to download the El Capitan file from the link you posted above. I tried again today and got the same error message. The message appears about 1-2 seconds after starting the download. When I do the download, I have Application and ISO checked.

It appears that I can download High Sierra, but not Sierra, El Capitan, or Yosemite

<img width="799" alt="Screenshot 2023-06-09 at 10 36 46 AM" src="https://github.com/ninxsoft/Mist/assets/136063852/a5f67f40-27f6-4116-a578-d519945f08be">
<img width="484" alt="Screenshot 2023-06-09 at 10 37 44 AM" src="https://github.com/ninxsoft/Mist/assets/136063852/d3b319d2-5bc1-4f93-abdc-1560a70379c5">

**Comment by ninxsoft** [comment]
@BenFRC5147 + @AKERDoc thanks for providing the requested information 🙌

Screen capture was referring to a video recording of the issue (@BenFRC5147 shared a YouTube link above)

I still cannot replicate this issue, so will keep digging and hopefully report back with a path forward soon 👍

**Comment by F1248** [comment]
I get exactly the same error with OS X Yosemite, El Capitan and Sierra, all other versions work fine.

- MacBook Air M1 (MacBookAir10,1)
- macOS 13.4 (22F66)
- Mist 0.8

**Comment by BenFRC5147** [comment]
Issue also occurs with a freshly imaged mac on Monterey MacBook air 13 inch early 2015, 1.6ghz core i5

**Comment by crystall1nedev** [comment]
This is the error:

```
Task <4CC4CD3A-F326-440F-B91D-334877834314>.<2> finished with error [-1022] Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, NSUnderlyingError=0x6000033b0210 {Error Domain=kCFErrorDomainCFNetwork Code=-1022}}
```

Took a little bit of time in Console.app to find what was going wrong.

**Comment by crystall1nedev** [comment]
This is caused by you using an HTTP link while App Transport Security is enabled. A simple fix would be to add the required keys to your Info.plist - but that also means that bad actors could cause man-in-the-middle situations if they really wanted to.

**Comment by ninxsoft** [comment]
@crystall1nedev nicely done!

This tracks, as it appears I have typos in my URLs for **OS X Yosemite**, **OS X El Capitan** and **macOS Sierra**:

https://github.com/ninxsoft/Mist/blob/67ae0c2e2cf22c1d9ec8016223dece1b11f61cb6/Mist/Model/Installer.swift#L153
https://github.com/ninxsoft/Mist/blob/67ae0c2e2cf22c1d9ec8016223dece1b11f61cb6/Mist/Model/Installer.swift#L246
https://github.com/ninxsoft/Mist/blob/67ae0c2e2cf22c1d9ec8016223dece1b11f61cb6/Mist/Model/Installer.swift#L354

Or rather, I am using the URLs provided by Apple from https://support.apple.com/en-us/HT211683

Switching to `https` should just work 🤔

**Comment by ninxsoft** [comment]
Maybe not - those URLs are not being served over HTTPS 👎

The good news is that it looks like `http://updates-http.cdn-apple.com/...` can be swapped out for `https://updates.cdn-apple.com/...`, like the URLs provided for **Mac OS X Lion** and **Mac OS X Mountain Lion**

Currently testing - if this works, no need to modify any App Transport Security settings 🤞

**Comment by AKERDoc** [comment]
It now worked perfectly downloading El Capitan. Thank you very much!
