### ISSUE TITLE
Request: Change ownership of generated folders & files on completion

### ISSUE THREAD

**Issue by carlashley** [ninxsoft/Mist#47]
I'm only filing this because I'm lazy and I'd prefer not to have to remember to `chown -R [installer_folder]` after building an Intel installer app, could `mist` automatically change ownership (recursively) on the folder that the installer app gets dropped into so it's no longer `root:[group]`?

**Comment by Serena-io** [comment]
doesn’t sound hard to do at all, actually sounds very doable but, the question should be more really, is it worth the effort? I feel like it would be too niche of an option :/

**Comment by ninxsoft** [comment]
Voting **no** on this feature request for the following reasons:

- Changing ownership / permissions upon completion implies you have the permissions to do so in the first place. This potentially gets tricky when dealing with Apple firmware downloads, as they will soon no longer require `sudo` to download: #48
- Setting permissions for Intel downloads and not for Apple firmware downloads promotes feature disparity.
- `mist` builds / downloads files, at the temp / output directories specified. I feel modifying permissions is out of scope, best left up to the operating system / user to decide what to do (outside of `mist`).
- One wrong config and `mist` will be attempting to change ownership / permissions on incorrect paths. Do not want to deal with that!
- Don't be lazy 😛
