### ISSUE TITLE
Add `createinstallmedia` functionality to create USB Installer (Intel)

### ISSUE THREAD

**Issue by 5T33Z0** [ninxsoft/Mist#48]
### :bulb: Description

It would be cool if there was an option to create a USB installer once the macOS download is completed for those versions of OSX and macOS that support `createinstallmedia`

### :adhesive_bandage: Alternatives Solutions + Workarounds

Maybe a "Help" menu entry with a guide on how to create the Installer manually

### :information_source: Additional context

- OpenCore Legacy Patcher offers this feature: https://github.com/dortania/OpenCore-Legacy-Patcher

Thank you for this great app!

**Comment by ninxsoft** [comment]
Thanks for the suggestion - I like it + implementing this shouldn't be too challenging 🤞

I am currently tinkering with the UI, will report back once I have something to show 👍

**Comment by ninxsoft** [comment]
So far so good:

![1](https://github.com/ninxsoft/Mist/assets/4812595/e46fd987-9f9c-40a7-907b-e216c80f417e)
![2](https://github.com/ninxsoft/Mist/assets/4812595/cbc9eeed-9ec9-4043-89cf-0567db030587)
![3](https://github.com/ninxsoft/Mist/assets/4812595/c7331695-7919-48ac-86bc-17b6741ca495)
![4](https://github.com/ninxsoft/Mist/assets/4812595/086d35d3-824d-4965-be8f-523e62559989)

**Comment by 5T33Z0** [comment]
Incredible!
