### ISSUE TITLE
Add option to choose Cache directory

### ISSUE THREAD

**Issue by RedCSol** [ninxsoft/Mist#5]
Running macOS 12.3.1 on Macbook Pro 14 M1, already had earlier version of CLI-Mist installed. When I tried to download 12.5 using GUI Mist received an error that Cache folder could not be created. Was running GUI-Mist 0.2. Quit, deleted app, downloaded CLI-Mist 1.8 and installed, 0.2 GUI-Mist again and installed, now working. I assume the older CLI version was messing things up. It works now. Thanks for this excellent and extremely useful app!

**Comment by trodemaster** [comment]
I'm seeing this issue as well. Suspect that running mist-cli with sudo privs is creating a dir that the gui version can't remove. What is the path to the dir that the gui app is using for "cache"?

**Comment by kevinmcox** [comment]
`/Users/Shared/Mist/Cache/`

**Comment by RedCSol** [comment]
So I spoke too soon--it downloads 

`drwxrwxr-x  4 root  wheel   128 Aug 11 11:02 Mist`
I created a "Cache" directory within `/Users/Shared/Mist`
and the rights to "Cache" appear as 
`drwxrwxr-x  2 redc  wheel   64 Aug 11 11:02 Cache`
but at the end of the download process (12.5 firmware) in the GUI I get:
`Error: “UniversalMac_12.5_21G72_Restore.ipsw” couldn’t be moved because you don’t have permission to access “Mist”.`
The CLI works.

**Comment by trodemaster** [comment]
Ok, I confirmed that /Users/Shared/Mist was owned by root. I removed that directory and re-launched mist which allowed it to proceed to download.

**Comment by RedCSol** [comment]
deleted Mist folder from Shared, ran app and to download firmware and was prompted for location, created Mist folder using dialog and chose as target, download completely successfully. Thanks!

**Comment by Antediluvian** [comment]
> /Users/Shared/Mist/Cache/

Hi, is there any chance to change the location of this cache folder as I really don't have enough space in my internal SDD. Thank you very much.

**Comment by ninxsoft** [comment]
Here's my first attempt, so far so good!
![Screenshot 2022-09-23 at 1 20 30 pm](https://user-images.githubusercontent.com/4812595/191886246-45b33a23-2325-45d0-a11c-bea9e0dc1ff9.png)

**Comment by ninxsoft** [comment]
This has been added in d58bf5137a56440189e38b762456543ff492fcb1 👍
