### ISSUE TITLE
Extend `mist list` options to `mist download` for automation purposes

### ISSUE THREAD

**Issue by n8felton** [ninxsoft/Mist#50]
I'm debating with myself if this is necessary or not, so I wanted to propose it and see your thoughts.

I'm looking to have the `--export` and `--quiet` options that are available with `mist list` to be extended to `mist download`.

The idea is that if I were to automate the creation of install media, I would want the details of the download saved as an artifact.

For example, if I were to run `sudo mist download 12 --image --image-name 'Install_macOS_%VERSION%-%BUILD%.dmg' --quiet --export $PWD/export.json` the result would be same output as `mist list 12 --latest --quiet --export $PWD/export.json`, but with the details of what was downloaded.

My debate is if this is useful. Is it possible that the results of `mist list 12 --latest --quiet --export $PWD/export.json` would be different than what would be downloaded with `sudo mist download 12 --image --image-name 'Install_macOS_%VERSION%-%BUILD%.dmg' --quiet --export $PWD/export.json`?

Another thought I had was to have an option to export as environment variables for the 3 variables that can be used with names, something like $MIST_NAME, $MIST_VERSION, $MIST_BUILD that would be the same as %NAME%, %VERSION%, %BUILD%.

**Comment by ninxsoft** [comment]
I like the idea of exporting the `mist download` output to a json/yaml file, complete with the following:

- Downloaded file(s) + sizes + paths
- Temp file(s) created
- Generated app + dmg + pkg paths

In theory, this exported (structured) output can be consumed by some other system for reporting / analytics etc.

Also like the optional `--quiet` flag to suppress standard output.

Will look into this!

**Comment by ninxsoft** [comment]
Finally got some traction!
- `mist download --quiet` will suppress all standard output
- `mist download --export  <export>` will export the downloaded Firmware / Installer and provided options

Here's an example of a successfully downloaded macOS Firmware IPSW file:

```json
{
  "firmware" : {
    "beta" : false,
    "build" : "21D62",
    "date" : "2022-02-10T18:25:00Z",
    "name" : "macOS Monterey",
    "signed" : true,
    "size" : 14139692117,
    "url" : "https:\/\/updates.cdn-apple.com\/2022WinterFCS\/fullrestores\/002-66272\/FB0B40F5-49EB-421B-81EC-8B56B8468D3C\/UniversalMac_12.2.1_21D62_Restore.ipsw",
    "version" : "12.2.1"
  },
  "options" : {
    "exportPath" : "\/Users\/nindi\/Desktop\/mist-firmware.json",
    "firmwarePath" : "\/Users\/Shared\/Mist\/macOS Monterey-12.2.1-21D62.ipsw",
    "force" : true,
    "includeBetas" : true,
    "keychain" : "",
    "kind" : "firmware",
    "outputDirectory" : "\/Users\/Shared\/Mist",
    "quiet" : true,
    "temporaryDirectory" : "\/private\/tmp\/com.ninxsoft.mist.12.2.1-21D62"
  }
}
```

And here's an example of a successfully downloaded macOS Installer Application Bundle:

```json
{
  "installer" : {
    "beta" : false,
    "build" : "21D62",
    "date" : "2022-02-18",
    "distribution" : "https:\/\/swdist.apple.com\/content\/downloads\/11\/62\/002-66265-A_HKQGKQG1Z4\/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93\/002-66265.English.dist",
    "identifier" : "002-66265",
    "name" : "macOS Monterey",
    "packages" : [
      {
        "size" : 5119,
        "url" : "https:\/\/swcdn.apple.com\/content\/downloads\/11\/62\/002-66265-A_HKQGKQG1Z4\/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93\/Info.plist"
      },
      {
        "size" : 1290934,
        "url" : "https:\/\/swcdn.apple.com\/content\/downloads\/11\/62\/002-66265-A_HKQGKQG1Z4\/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93\/MajorOSInfo.pkg"
      },
      {
        "size" : 188,
        "url" : "https:\/\/swcdn.apple.com\/content\/downloads\/11\/62\/002-66265-A_HKQGKQG1Z4\/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93\/InstallInfo.plist"
      },
      {
        "size" : 12155426708,
        "url" : "https:\/\/swcdn.apple.com\/content\/downloads\/11\/62\/002-66265-A_HKQGKQG1Z4\/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93\/InstallAssistant.pkg"
      },
      {
        "size" : 2764685,
        "url" : "https:\/\/swcdn.apple.com\/content\/downloads\/11\/62\/002-66265-A_HKQGKQG1Z4\/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93\/UpdateBrain.zip"
      },
      {
        "size" : 1945574,
        "url" : "https:\/\/swcdn.apple.com\/content\/downloads\/11\/62\/002-66265-A_HKQGKQG1Z4\/orfaxf4k2gvqeatuhx6agnr5nlti3rwq93\/BuildManifest.plist"
      }
    ],
    "size" : 12161433208,
    "version" : "12.2.1"
  },
  "options" : {
    "application" : true,
    "applicationPath" : "\/Users\/Shared\/Mist\/macOS Monterey-12.2.1-21D62.app",
    "catalogURL" : "https:\/\/swscan.apple.com\/content\/catalogs\/others\/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz",
    "exportPath" : "\/Users\/Shared\/Mist\/mist-installer.json",
    "force" : true,
    "image" : true,
    "imagePath" : "\/Users\/Shared\/Mist\/macOS Monterey-12.2.1-21D62.dmg",
    "imageSigningIdentity" : "Developer ID Application: Nindi Gill (7K3HVCLV7Z)",
    "includeBetas" : true,
    "iso" : true,
    "isoPath" : "\/Users\/Shared\/Mist\/macOS Monterey-12.2.1-21D62.iso",
    "keychain" : "",
    "kind" : "installer",
    "outputDirectory" : "\/Users\/Shared\/Mist",
    "package" : true,
    "packageIdentifier" : "com.ninxsoft.macos-monterey-12.2.1-21d62",
    "packagePath" : "\/Users\/Shared\/Mist\/macOS Monterey-12.2.1-21D62.pkg",
    "packageSigningIdentity" : "Developer ID Installer: Nindi Gill (7K3HVCLV7Z)",
    "quiet" : true,
    "temporaryDirectory" : "\/private\/tmp\/002-66265"
  }
}
```

**Note:** Any error along the way will result in `mist` throwing an exception, and exiting early (thus not exporting any results).
