### ISSUE TITLE
Cannot create Monterey ISO Installer

### ISSUE THREAD

**Issue by phonegi** [ninxsoft/Mist#51]
### :beetle: Description

When attempting to create ISO installer for any version of macOS Monterey, the process fails.

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
2. Firmwares and Installers successfully update
3. Select Installers
4. Click "Download" button next to any version of Monterey
5. In "Select Export Types", select ONLY ISO. No other boxes selected
6. Click "Save"
7. All steps complete successfully until ISO - Create macOS Installer in temporary Disk Image. This step fails with a popup that says, "An error has occurred! Invalid Termination Status: 9"

### :white_check_mark: Expected Behaviour

The ISO Installer should be created

### :computer: Environment

- Mist version (0.7, but this was also occurring in v0.6)
- macOS Version (13.4)
- Hardware
  - Model Identifier: Macmini8,1
  - Chip : 6-Core Intel Core i7

### :camera: Screenshots
![image](https://github.com/ninxsoft/Mist/assets/453317/4446ea1a-ce54-4526-8104-f6bbe48b78be)
![image](https://github.com/ninxsoft/Mist/assets/453317/44730579-a32a-427c-ab70-a0086a3cccd2)

**Comment by ninxsoft** [comment]
I suspect the termination status `9` refers to a [SIGKILL](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGKILL) terminating the process that is being used to create the macOS Installer.

Using the command from the [Create a bootable installer for macOS](https://support.apple.com/en-us/HT201372) article, are you able to confirm if you also receive the same termination status of `9`?

**Note:** You will need a copy of the macOS Monterey installer application, which you can export from Mist. You will also need to either create and mount a 14GB+ disk image, or use a 14GB+ USB drive if you have one to spare.
