### ISSUE TITLE
Clear Cache Addition

### ISSUE THREAD

**Issue by dracinn** [ninxsoft/Mist#59]
I would like the ability to remove certain macOS versions from cache i.e. when clicking on clear cache we could select all or certain versions.

**Comment by ninxsoft** [comment]
Sounds like a neat idea - will tinker with what the UI could look like and report back once I have something 👍

Thanks!

**Comment by ninxsoft** [comment]
Progress!

![Caching](https://github.com/ninxsoft/Mist/assets/4812595/4a233ec1-5aa1-4f07-b826-0b00ad78bafc)
![Caching Confirmation](https://github.com/ninxsoft/Mist/assets/4812595/d11f2466-ca33-492f-bd2a-6102d7ec8480)
