### ISSUE TITLE
Crashing at download

### ISSUE THREAD

**Issue by RedCSol** [ninxsoft/Mist#6]
My colleague is getting a crash when she tries downloading IPSW or other formats. Crash report below

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Mist [82064]
Path:                  /Applications/Mist.app/Contents/MacOS/Mist
Identifier:            com.ninxsoft.mist
Version:               0.2 (0.2)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2022-08-12 15:20:12.8051 -0700
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        B51BBE54-EF2C-4A14-A267-476EC564F945

Sleep/Wake UUID:       1CD7F04D-ABA6-4CA9-A9E5-03034A322870

Time Awake Since Boot: 550000 seconds
Time Since Wake:       2721 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000197afda18
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [82064]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libunwind.dylib               	       0x197afda18 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step() + 680
1   libunwind.dylib               	       0x197afd7a0 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step() + 48
2   libobjc.A.dylib               	       0x18cf7362c objc_addExceptionHandler + 68
3   AppKit                        	       0x18ffa21c0 -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:] + 912
4   AppKit                        	       0x18ffa1d90 __35-[NSApplication runModalForWindow:]_block_invoke_2 + 44
5   AppKit                        	       0x18ffa1d48 __35-[NSApplication runModalForWindow:]_block_invoke + 112
6   AppKit                        	       0x18ffa14d8 _NSTryRunModal + 128
7   AppKit                        	       0x18ffa1388 -[NSApplication runModalForWindow:] + 148
8   AppKit                        	       0x190721058 -[NSSavePanel runModal] + 552
9   Mist                          	       0x1028f4a84 0x102890000 + 412292
10  Mist                          	       0x1028f5955 0x102890000 + 416085
11  libswift_Concurrency.dylib    	       0x20b050959 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 1:
0   libsystem_pthread.dylib       	       0x18d0cc010 start_wqthread + 0

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x18d095954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x18d095d00 mach_msg + 76
2   CoreFoundation                	       0x18d19ced8 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x18d19b390 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x18d19a734 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x18fe5dfb0 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x18d0d1240 _pthread_start + 148
7   libsystem_pthread.dylib       	       0x18d0cc024 thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x18d0cc010 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x18d0cc010 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x18d0cc010 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x18d0cc010 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x18d0cc010 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x18d0cc010 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000016d56d240   x1: 0x0000000197afd770   x2: 0x00000001e8031f30   x3: 0x000000000000003c
    x4: 0x000000000000290c   x5: 0x0000000000000000   x6: 0x6e69746c6975625f   x7: 0x0000000000000b50
    x8: 0x000000016d56d350   x9: 0x100000016d56e0d0  x10: 0xd21f00020b04b7b0  x11: 0x100000016d56e088
   x12: 0x000000014703cc60  x13: 0x000000020b04ada0  x14: 0x000000020b04ac54  x15: 0x0000000004000007
   x16: 0x400000020b04b7b0  x17: 0x000000020b04b7b0  x18: 0x000000014880b940  x19: 0x000000016d56d240
   x20: 0xdd2b000190721057  x21: 0x0000000000000001  x22: 0x00000000000003b4  x23: 0x0000000000000000
   x24: 0x0000000000000028  x25: 0x0000000190927d15  x26: 0x000000019072120c  x27: 0x00000001907211e4
   x28: 0x0000000190927d5e   fp: 0x000000016d56d180   lr: 0x0000000197afd7a0
    sp: 0x000000016d56bc70   pc: 0x0000000197afda18 cpsr: 0x20001000
   far: 0x0000000102a3e878  esr: 0xf200c471 (Breakpoint) pointer authentication trap IB

Binary Images:
       0x197af6000 -        0x197b00fff libunwind.dylib (*) <cf584b24-4773-3e77-9aec-8dde83a3c376> /usr/lib/system/libunwind.dylib
       0x18cf56000 -        0x18cf91fff libobjc.A.dylib (*) <2eb32e1d-90cb-3256-8681-9034085a06a6> /usr/lib/libobjc.A.dylib
       0x18fcaf000 -        0x190b65fff com.apple.AppKit (6.9) <8701760d-31b6-37eb-be77-ffb39921dd22> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x102890000 -        0x102a4bfff com.ninxsoft.mist (0.2) <8def3962-1987-339d-973e-65e3cec548a5> /Applications/Mist.app/Contents/MacOS/Mist
       0x20b00d000 -        0x20b060fff libswift_Concurrency.dylib (*) <50b9f80c-f39b-3792-b642-1ff1684a50b3> /usr/lib/swift/libswift_Concurrency.dylib
       0x18d0ca000 -        0x18d0d6fff libsystem_pthread.dylib (*) <f7b2eccf-e6f1-3109-ae81-9028c0b8332a> /usr/lib/system/libsystem_pthread.dylib
       0x18d094000 -        0x18d0c9fff libsystem_kernel.dylib (*) <384945e6-dd71-37e5-9a3d-84fff14a1e60> /usr/lib/system/libsystem_kernel.dylib
       0x18d118000 -        0x18d65bfff com.apple.CoreFoundation (6.9) <35473de6-c433-332c-aee0-013fd5f6d4fd> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=334.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=334.9M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 3136K        8 
CG image                           400K       21 
ColorSync                          640K       28 
CoreAnimation                     2720K      165 
CoreGraphics                        48K        3 
CoreUI image data                 3072K       40 
Dispatch continuations            64.0M        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           187.5M       85 
MALLOC guard page                  288K       16 
MALLOC_MEDIUM (reserved)          56.0M        1         reserved VM address space (unallocated)
SQLite page cache                  320K        5 
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                        1.0G       28 
__AUTH                            2668K      315 
__AUTH_CONST                      19.9M      501 
__DATA                            15.6M      488 
__DATA_CONST                      17.4M      507 
__DATA_DIRTY                      1799K      206 
__FONT_DATA                          4K        1 
__LINKEDIT                       576.4M        5 
__OBJC_CONST                      3328K      268 
__OBJC_RO                         82.1M        1 
__OBJC_RW                         3104K        1 
__TEXT                           477.0M      525 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
libnetwork                        5760K       32 
mapped file                      166.2M       32 
shared memory                     3408K       14 
===========                     =======  ======= 
TOTAL                              2.7G     3323 
TOTAL, minus reserved VM space     2.7G     3323 

-----------
Full Report
-----------

{"app_name":"Mist","timestamp":"2022-08-12 15:20:13.00 -0700","app_version":"0.2","slice_uuid":"8def3962-1987-339d-973e-65e3cec548a5","build_version":"0.2","platform":1,"bundleID":"com.ninxsoft.mist","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.2.1 (21D62)","incident_id":"04322CE9-4DF3-44E3-966A-1F30AFA488DF","name":"Mist"}
{
  "uptime" : 550000,
  "procLaunch" : "2022-08-12 15:19:53.4631 -0700",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 13364799540739,
  "coalitionID" : 49893,
  "osVersion" : {
    "train" : "macOS 12.2.1",
    "build" : "21D62",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-12 15:20:12.8051 -0700",
  "incident" : "04322CE9-4DF3-44E3-966A-1F30AFA488DF",
  "bug_type" : "309",
  "pid" : 82064,
  "procExitAbsTime" : 13365263716751,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Mist",
  "procPath" : "\/Applications\/Mist.app\/Contents\/MacOS\/Mist",
  "bundleInfo" : {"CFBundleShortVersionString":"0.2","CFBundleVersion":"0.2","CFBundleIdentifier":"com.ninxsoft.mist"},
  "storeInfo" : {"deviceIdentifierForVendor":"6E26C384-AE2D-510C-A934-9EBAEAF176F9","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.ninxsoft.mist",
  "crashReporterKey" : "B51BBE54-EF2C-4A14-A267-476EC564F945",
  "wakeTime" : 2721,
  "sleepWakeUUID" : "1CD7F04D-ABA6-4CA9-A9E5-03034A322870",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000197afda18","rawCodes":[1,6839851544],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":82064},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":5298599,"threadState":{"x":[{"value":6129373760},{"value":6839850864,"symbolLocation":0,"symbol":"libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step()"},{"value":8187486000,"symbolLocation":80,"symbol":"vtable for libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>"},{"value":60},{"value":10508},{"value":0},{"value":7956018225701282399},{"value":2896},{"value":6129374032},{"value":1152921510736224464},{"value":15140820481017690032,"symbolLocation":15140820472242896972,"symbol":"swift_job_runImpl(swift::Job*, swift::ExecutorRef)"},{"value":1152921510736224392},{"value":5486398560},{"value":8774790560,"symbolLocation":0,"symbol":"swift::AsyncTask::flagAsRunning()"},{"value":8774790228,"symbolLocation":0,"symbol":"swift::runJobInEstablishedExecutorContext(swift::Job*)"},{"value":67108871},{"value":4611686027202181040,"symbolLocation":4611686018427387980,"symbol":"swift_job_runImpl(swift::Job*, swift::ExecutorRef)"},{"value":8774793136,"symbolLocation":76,"symbol":"swift_job_runImpl(swift::Job*, swift::ExecutorRef)"},{"value":5511362880},{"value":6129373760},{"value":15936831713098993751,"symbolLocation":15936831706380632615,"symbol":"-[NSSavePanel runModal]"},{"value":1},{"value":948},{"value":0},{"value":40},{"value":6720486677,"symbolLocation":5,"symbol":"GCC_except_table140"},{"value":6718362124,"symbolLocation":0,"symbol":"__23-[NSSavePanel runModal]_block_invoke"},{"value":6718362084,"symbolLocation":948,"symbol":"-[NSSavePanel runModal]"},{"value":6720486750,"symbolLocation":78,"symbol":"GCC_except_table140"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6839850912},"cpsr":{"value":536875008},"fp":{"value":6129373568},"sp":{"value":6129368176},"esr":{"value":4060136561,"description":"(Breakpoint) pointer authentication trap IB"},"pc":{"value":6839851544,"matchesCrashFrame":1},"far":{"value":4339263608}},"queue":"com.apple.main-thread","frames":[{"imageOffset":31256,"symbol":"libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step()","symbolLocation":680,"imageIndex":0},{"imageOffset":30624,"symbol":"libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm64>::step()","symbolLocation":48,"imageIndex":0},{"imageOffset":120364,"symbol":"objc_addExceptionHandler","symbolLocation":68,"imageIndex":1},{"imageOffset":3092928,"symbol":"-[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:]","symbolLocation":912,"imageIndex":2},{"imageOffset":3091856,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke_2","symbolLocation":44,"imageIndex":2},{"imageOffset":3091784,"symbol":"__35-[NSApplication runModalForWindow:]_block_invoke","symbolLocation":112,"imageIndex":2},{"imageOffset":3089624,"symbol":"_NSTryRunModal","symbolLocation":128,"imageIndex":2},{"imageOffset":3089288,"symbol":"-[NSApplication runModalForWindow:]","symbolLocation":148,"imageIndex":2},{"imageOffset":10952792,"symbol":"-[NSSavePanel runModal]","symbolLocation":552,"imageIndex":2},{"imageOffset":412292,"imageIndex":3},{"imageOffset":416085,"imageIndex":3},{"imageOffset":276825,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":4}]},{"id":5298681,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":5298684,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":544472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":7},{"imageOffset":537488,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":7},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":7},{"imageOffset":1765296,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":2},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":5298685,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":5298688,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":5298838,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":5298839,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":5298900,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":5298901,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6839820288,
    "size" : 45056,
    "uuid" : "cf584b24-4773-3e77-9aec-8dde83a3c376",
    "path" : "\/usr\/lib\/system\/libunwind.dylib",
    "name" : "libunwind.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6659858432,
    "size" : 245760,
    "uuid" : "2eb32e1d-90cb-3256-8681-9034085a06a6",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6707408896,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15429632,
    "uuid" : "8701760d-31b6-37eb-be77-ffb39921dd22",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.30.116"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4337500160,
    "CFBundleShortVersionString" : "0.2",
    "CFBundleIdentifier" : "com.ninxsoft.mist",
    "size" : 1818624,
    "uuid" : "8def3962-1987-339d-973e-65e3cec548a5",
    "path" : "\/Applications\/Mist.app\/Contents\/MacOS\/Mist",
    "name" : "Mist",
    "CFBundleVersion" : "0.2"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8774537216,
    "size" : 344064,
    "uuid" : "50b9f80c-f39b-3792-b642-1ff1684a50b3",
    "path" : "\/usr\/lib\/swift\/libswift_Concurrency.dylib",
    "name" : "libswift_Concurrency.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6661382144,
    "size" : 53248,
    "uuid" : "f7b2eccf-e6f1-3109-ae81-9028c0b8332a",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6661160960,
    "size" : 221184,
    "uuid" : "384945e6-dd71-37e5-9a3d-84fff14a1e60",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6661701632,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "35473de6-c433-332c-aee0-013fd5f6d4fd",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.107"
  }
],
  "sharedCache" : {
  "base" : 6658211840,
  "size" : 3091218432,
  "uuid" : "296eb28e-6aeb-3129-8fa6-feb92261a4eb"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=334.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=334.9M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 3136K        8 \nCG image                           400K       21 \nColorSync                          640K       28 \nCoreAnimation                     2720K      165 \nCoreGraphics                        48K        3 \nCoreUI image data                 3072K       40 \nDispatch continuations            64.0M        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           187.5M       85 \nMALLOC guard page                  288K       16 \nMALLOC_MEDIUM (reserved)          56.0M        1         reserved VM address space (unallocated)\nSQLite page cache                  320K        5 \nSTACK GUARD                       56.1M        9 \nStack                             12.2M        9 \nVM_ALLOCATE                        1.0G       28 \n__AUTH                            2668K      315 \n__AUTH_CONST                      19.9M      501 \n__DATA                            15.6M      488 \n__DATA_CONST                      17.4M      507 \n__DATA_DIRTY                      1799K      206 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       576.4M        5 \n__OBJC_CONST                      3328K      268 \n__OBJC_RO                         82.1M        1 \n__OBJC_RW                         3104K        1 \n__TEXT                           477.0M      525 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nlibnetwork                        5760K       32 \nmapped file                      166.2M       32 \nshared memory                     3408K       14 \n===========                     =======  ======= \nTOTAL                              2.7G     3323 \nTOTAL, minus reserved VM space     2.7G     3323 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000303
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "622657ce37186c771d5404ad"
      },
      "deploymentId" : 240000414
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000179
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000441
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 7429.81.3, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: DELL UP3017, 2560 x 1600, Main, MirrorOff, Online
Display: Color LCD, 2560 x 1600 Retina, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Oct 26 2021 16:10:41 version 18.20.310.15.7.8.120 FWID 01-5d6c3867
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: AX88179A, Ethernet, en7
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: NS1081
USB Device: AX88179A
USB Device: USB2.0 Hub
USB Device: Keychron C2
USB Device: Anker USB-C Hub Device
USB Device: USB31Bus
USB Device: billboard
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by ninxsoft** [comment]
@RedCSol unfortunately nothing is screaming out to me from the logs that could indicate the cause of the crash 🤔

Are you able to ask your colleague to test against [version 0.3](https://github.com/ninxsoft/Mist/releases/tag/v0.3) and see if the issue persists?

**Comment by ninxsoft** [comment]
Closing ticket due to inactivity - will re-open if @RedCSol requires further assistance 👍
