### ISSUE TITLE
Why is there no download connection provided for OS X Mavericks 10.9.5?

### ISSUE THREAD

**Issue by DevLiuSir** [ninxsoft/Mist#60]
Why is there no download connection provided for OS X Mavericks 10.9.5?

**Comment by ninxsoft** [comment]
Apple does not provide a download link for OS X Mavericks 10.9:

https://support.apple.com/en-us/HT211683

**Comment by DevLiuSir** [comment]
Oh. So that's it. Have you considered customizing a link for everyone to download?

**Comment by DevLiuSir** [comment]
Thank you! Have you considered customizing a link for everyone to download?

**Comment by F1248** [comment]
Here is a guide from Mr. Macintosh, 7. is about the difficulty with OS X Mavericks:
https://mrmacintosh.com/how-to-download-macos-catalina-mojave-or-high-sierra-full-installers/

**Comment by ninxsoft** [comment]
@DevLiuSir as there is no download link provided by Apple, I do not feel comfortable linking to a 3rd party source of OS X Mavericks 10.9, as I cannot verify it's integrity / shasum.

Happy to revisit if we stumble upon a OS X Mavericks installer provided by Apple 👍
