### ISSUE TITLE
Feature Request: Check Compatibility of Installers Against Current System

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#65]
This feature request is inspired by features added to a fork of `installinstallmacos.py` by @grahampugh: https://github.com/grahampugh/macadmin-scripts/blob/main/installinstallmacos.py

The ".sucatalog" file contains references to ".dist" files which are [Distribution XML](https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Introduction.html) files which normally exist within an installer package.

Within this XML structure, there is a section of [Installer JS](https://developer.apple.com/documentation/installer_js) (JavaScript code) which for Big Sur and newer ".dist" files contains JavaScript arrays of supported Board IDs ("board-id" within `ioreg -rc IOPlatformExpertDevice -d 1`) and Device IDs (the first element of the "compatible" array in `ioreg -rc IOPlatformExpertDevice -d 1` when run on Apple Silicon). For example from [002-77154.English.dist](https://swdist.apple.com/content/downloads/15/10/002-77154-A_LAKRVPO4Y6/dbmkv9538dfpvqaqdygjciw8775qjuytbh/002-77154.English.dist) for the macOS 11.6.5 Big Sur installer:
```
var supportedBoardIDs = ['Mac-C6F71043CEAA02A6', 'Mac-06F11F11946D27C5', ...];
var supportedDeviceIDs = ['J274AP', 'J215AP', ...];
```

For Catalina and older ".dist" files, this Installer JS code instead contains supported Board IDs and **_unsupported_** Model IDs (`sysctl -n hw.model`).  For example from [001-68446.English.dist](https://swdist.apple.com/content/downloads/26/37/001-68446/r1dbqtmf3mtpikjnd04cq31p4jk91dceh8/001-68446.English.dist) for the macOS 10.15.7 Catalina installer:
```
var boardIds = ['Mac-9AE82516C7C6B903','Mac-031B6874CF7F642A',...];
...
var nonSupportedModels = ['MacBookPro4,1','MacPro2,1',...];
```

These JavaScript arrays can be extracted and parsed to be able to have a list of compatible computers for each macOS installer. Here is the code to extract these values in @grahampugh's fork of `installinstallmacos.py`: https://github.com/grahampugh/macadmin-scripts/blob/ed6654e778ee2f0207e033e18f87b36ac4f4d8b8/installinstallmacos.py#L552 & https://github.com/grahampugh/macadmin-scripts/blob/ed6654e778ee2f0207e033e18f87b36ac4f4d8b8/installinstallmacos.py#L570 & https://github.com/grahampugh/macadmin-scripts/blob/ed6654e778ee2f0207e033e18f87b36ac4f4d8b8/installinstallmacos.py#L585

Once all of this data exists within `mist`, it would be possible to determine the compatibility of each macOS installer against the current Mac running `mist`.

I'm imagining this could result in new features in a few areas.

For `mist list`, I think it could be useful to add a "Compatible" column/field to the outputs which list Yes/No (or a boolean for output formats where that makes sense) to show whether or not each version of macOS is compatible with the current computer.

Also for `mist list`, I think it could be valuable to add `--only-compatible` and `--only-incompatible` options to only list the macOS installers that are either compatible or incompatible with the current computer.

For `mist download` a new argument wouldn't really fit with the current design since the version of macOS is normally specified with a search string. Instead of doing something like adding a custom "latest compatible" search string or anything, I'm thinking that could just be the new default state of `mist download` when run with no arguments. Currently, `mist download` will error when run with no arguments. Instead, I'm thinking it could be assumed the user wants the latest version of macOS that's compatible with the current computer and just start downloading it instead of erroring.

All of the above details about ".dist" files only applies to Installer Applications since I don't believe the same data is easily available from Apple for IPSW Firmwares for Apple Silicon. But, the IPSW.me v4 API could be used to be able to get compatible IPSWs when queried with the Model ID of the current Mac (such as https://api.ipsw.me/v4/device/Mac13,1?type=ipsw vs https://api.ipsw.me/v4/device/MacBookPro18,4?type=ipsw vs https://api.ipsw.me/v4/device/MacBookPro17,1?type=ipsw). Even though all Apple Silicon Macs currently support the newest version of macOS, this could still be a valuable check to do since only the version of macOS that each model originally shipped with and newer are compatible with that Mac model. With both a list of all IPSWs available and a list of IPSWs only compatible with the current Mac model, the same info could be obtained for the `mist list -k ipsw` output and options. To download the "latest compatible" IPSW with `mist download -k ipsw`, just the IPSW.me v4 API could be queried for the Model ID (without needing to also retrieve all possible IPSWs) when running on an Apple Silicon Mac. This would be future-proof for when some Apple Silicon Macs don't support the latest version of macOS, even though they all currently do. When that command with no other args is run on an Intel Mac, the latest IPSW could just be downloaded for reasonably consistent behavior.

Thanks for considering this new feature and functionality!

**Comment by PicoMitchell** [comment]
I forgot to mention for full disclosure that the addition of this feature would allow @grahampugh to be able to replace the use of their `installinstallmacos.py` fork in [erase-install](https://github.com/grahampugh/erase-install) with this possible future version of `mist` which has the ability to download the latest version of macOS that's compatible with the currently running Mac. This would be pretty cool for `erase-install` and its users since it would no longer require Python. But, I also think these features would add value to other users and use cases.

**Comment by PicoMitchell** [comment]
Looks like I missed that Device IDs could also be used for T2 Macs, not only Apple Silicon Macs. For T2 Macs, it appears to be the Bridge ID from `/usr/libexec/remotectl get-property localbridge HWModel` (https://github.com/grahampugh/macadmin-scripts/blob/ed6654e778ee2f0207e033e18f87b36ac4f4d8b8/installinstallmacos.py#L148).

Here is where all the checks happen in the `installinstallmacos.py` fork once all the values have been retrieved from the ".dist" files as well as from the current Mac: https://github.com/grahampugh/macadmin-scripts/blob/ed6654e778ee2f0207e033e18f87b36ac4f4d8b8/installinstallmacos.py#L991

**Comment by ninxsoft** [comment]
Finally starting to wrap my head around Board IDs, Device IDs and Bridge IDs - @PicoMitchell / @grahampugh hoping you can fact check me on the following:

**Board ID**
* Follows the format `Mac-XXXXXXXXXXXXXXXX` where `X` is a hexadecimal character
* Present on Intel Macs **only**
* Can be obtained using `ioreg -rc IOPlatformExpertDevice -d 1 | grep board-id | awk -F\" '{ print $4 }'`
* Maps 1:1 to a **ModelIdentifier** (ie. `sysctl -n hw.model`)

**Device ID**
* *Generally* follows the format `JXXXAP` where `X` is a numerical character
* Present on Apple Silicon Macs **only**
* Can be obtained using `ioreg -rc IOPlatformExpertDevice -d 1 | grep compatible | awk -F\" '{ print $4 }'`
* Maps 1:1 to a **ModelIdentifier** (ie. `sysctl -n hw.model`)

**Bridge ID**
* *Generally* follows the format `JXXXAP` where `X` is a numerical character
  * Same format as the Device ID
* Present on Intel Macs with a T2 chip **only**
* Can be obtained using `/usr/libexec/remotectl get-property localbridge HWModel`
* Maps 1:1 to a **ModelIdentifier** (ie. `sysctl -n hw.model`)

Assuming the above is accurate, my pseudocode to determine compatibility is as follows:

```
for each macOS installer
    if (known-board-ids is not empty) and (mac is intel) and (known-board-ids does not contain mac-board-id)
        return false
    end if

    if (known-device-ids is not empty) and (mac is apple silicon) and (known-device-ids does not contain mac-device-id)
        return false
    end if

    if (known-device-ids is not empty) and (mac is intel) and (mac is T2) and (known-device-ids does not contain mac-device-id)
        return false
    end if

    if (known-model-identifiers is not empty) and (known-model-identifiers does not contain mac-model-identifier)
        return false
    end if

    return true
end for
```

Alternatively, I am tempted to investigate transforming Board IDs / Device IDs / Bridge IDs into their Model Identifier counterparts (via some lookup) - this will keep the codebase much simpler but will require maintenance 🤔

**Comment by PicoMitchell** [comment]
I believe all of your descriptions and logic there is correct, except I think that Board/Device/Bridge IDs may not always be a 1:1 relationship with Model IDs, but sometimes a Many-to-One relationship (not that that makes a big difference to any of your thinking here).

If you decided to instead base the supported OS logic on Model IDs, it would basically mean having to keep track manually and update `mist` every time a new Mac model and new version of macOS came out. It could work fine, but using the data Board/Device/Bridge IDs that are embedded in the ".dist" files would be future and past proof without `mist` needing to be updated to support new Macs or macOS versions.

**Comment by PicoMitchell** [comment]
Thinking though how to properly base your code on Model IDs only, I'm not sure it would make for  much simpler code or logic.

To accommodate every possible installer, some of which are Model-specific builds and only support a few IDs, you would either need to have a database of every existing installer and the Model IDs each one supports, or you would need to have a database of every Board/Device/Bridge ID and which Model ID it correlates to.

The former would eliminate the need to load every ".dist" file dynamically in `mist` since it would know in advance which Model is supported by each installer and `mist` would only need to retrieve the current Macs Model ID. But, that would mean you would need to maintain that database and `mist` would need to be updated each time a new Mac Model or macOS update came out (but you could make some assumptions about some macOS betas and minor versions).

The latter would still need to load all the ".dist" files manually to get the supported Board/Device/Bridge IDs but would eliminate is retrieving the current Macs Board/Device/Bridge IDs from `ioreg` or `remotectl` and you would only need the Model ID. But, this would still require updating `mist` more frequently every time a new Mac model came out to keep your Board/Device/Bridge IDs to Model IDs database up-to-date.

**Comment by ninxsoft** [comment]
@PicoMitchell thanks for clarifying my logic, and you bring up some great points - I am already loading each **.dist** file for other bits of information, so it isn't too much extra code (plus I already have a working model, so I'm just nitpicking at this stage 😛).

Regarding `mist list`:
* I like the idea of an extra "Compatible" column, displaying `true`/`false` for each macOS Installer. The same goes for exporting lists to **csv** / **json** / **plist** / **yaml**.
* The `--only-compatible`/`--hide-incompatible` flag makes sense, displaying / exporting compatible builds only.
* I am not sold on `--only-incompatible`, as I cannot think of a use case. Also not sure what the behaviour should be if `--only-compatible` and `--only-incompatible` flags were both supplied. Happy to be convinced otherwise though.

Regarding `mist download`:
* I feel defaulting a blank `<search-string>` to the latest compatible build will potentially confuse users.
* I am leaning towards a `--latest-compatible` flag, which will filter down to the first compatible installer, based on the `<search-string>` input.

Regarding firmwares:
* https://api.ipsw.me/v4/device/$MODELIDENTIFIER?type=ipsw seems reasonable, just need to test.

**Comment by ninxsoft** [comment]
Compatibility checks for firmwares: 6ad69e5

**Comment by PicoMitchell** [comment]
I don't really have a strong argument for `--only-incompatible`, I think I only included that for the sake of completeness.

**Comment by ninxsoft** [comment]
Thanks for the clarification @PicoMitchell! My logic matches non supported models, but yes, in the context of my pseudocode, `known-model-identifiers` should refer to non supported models 👍
