### ISSUE TITLE
Quick question about download urls being used

### ISSUE THREAD

**Issue by NorseGaud** [ninxsoft/Mist#66]
Downloading with mist from Israel is awfully slow. I'm guessing this is just downloading from the apple mirrors? Can someone confirm?

**Comment by n8felton** [comment]
Yes, by default, Mist is using Apple's public software update servers.

https://github.com/ninxsoft/Mist/blob/ec462cff3ba4548ccdeddba46b465965cb8b3eb2/Mist/Model/Catalog.swift#L21-L32

This can be changed using the `-c, --catalog-url <catalog-url>` option, perhaps to a local copy using [reposado](https://github.com/wdas/reposado)
