### ISSUE TITLE
mist 1.7 is not a Universal Binary

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#69]
When on Apple Silicon without Rosetta 2 installed, `mist` cannot run:
```
% mist
zsh: bad CPU type in executable: mist
% file $(which mist)
/usr/local/bin/mist: Mach-O 64-bit executable x86_64
```

After installing Rosetta 2, `mist` works fine. But, it seems like Rosetta shouldn't be a requirement for a tool like this.

**Comment by ninxsoft** [comment]
Great pickup! Turns out `mist` was being being built only for x86_64:

```bash
➜ ~ lipo -archs /usr/local/bin/mist                                                         
x86_64
```

This is an easy fix, just need to add the `--arch` flag to the `swift build` command in the Makefile, which will produces the following output:

```bash
➜ ~ lipo -archs /usr/local/bin/mist                                                         
x86_64 arm64
```

**Comment by ninxsoft** [comment]
Binary and package have approximately doubled in size! Still worth it as Rosetta is no longer a prerequisite for Apple Silicon 👍

**Comment by ninxsoft** [comment]
Next release will be compiled as a Universal binary
