### ISSUE TITLE
Mist and mist-cli packages have identical pkgid

### ISSUE THREAD

**Issue by oliverweinm** [ninxsoft/Mist#7]
Hi guys,

as can be seen in the Info.plist for the Mist.pkg (v0.2) and the mist-cli.pkg(v1.8), both packages have the identical pkg identifier _com.ninxsoft.mist_.
Due to this, software deployment frameworks like Munki exhibit unwanted behaviour (i.e. uninstalling both when only one is supposed to be uninstalled) since it can effectively not distinguish both from each other due to their identical 
If you could change the pkgid for either of the packages, that would be very appreciated!

Thanks in advance
![Screenshot 2022-08-14 at 22 09 51](https://user-images.githubusercontent.com/55440219/184553194-998d0ccc-1c1b-482a-ab1f-aa481aa5798e.png)
![Screenshot 2022-08-14 at 22 11 38](https://user-images.githubusercontent.com/55440219/184553249-71ccbe13-6bf5-4b2b-b396-87ab2fcb8309.png)

**Comment by ninxsoft** [comment]
Hi @oliverweinm, thanks for the heads up!

I feel the easy solution is to rename the CLI package identifier to `com.ninxsoft.pkg.mist-cli`

This will be reflected in the next release 👍

**Comment by ninxsoft** [comment]
See: https://github.com/ninxsoft/mist-cli/commit/8841db092b9659543a71132840b4a9abc4790809

**Comment by oliverweinm** [comment]
Thanks a lot! That should work.
