### ISSUE TITLE
ISO Images No Longer Bootable

### ISSUE THREAD

**Issue by mviron** [ninxsoft/Mist#74]
Created ISO image only, and the ISO image created for several versions (11.7.8, 10.10, 10.11) were not bootable when creating a virtual machine.  ISOs created in versions prior to .9 did boot.

**Comment by jnichols35** [comment]
I'm also having this issue. I tried downgrading to the previous release, but it's having the same issue.

**Comment by tulgeywood** [comment]
I'm pretty sure this is something wrong with the DMGs that get created. I tried making my own bootable ISO from the DMG via hdiutil and the resulting ISO would still not work. Additionally the ISO ends up mounting with a numerical name instead of the standard "Install macOS..."

**Comment by 4yt1k** [comment]
I download and create iso file is ok,but the iso file can't install on vmware.

**Comment by tranphuquy19** [comment]
I had a similar issue and was able to resolve it by downloading Mist v0.8.1.

**Comment by ninxsoft** [comment]
The logic I was using to shrink the Bootable Disk Image down in size seems to have broken the ability to boot the ISOs.

I have a pull request in flight, #82, will reach out to confirm testing after I cut a new release 👍

**Comment by ninxsoft** [comment]
[Mist version 0.9.1](https://github.com/ninxsoft/Mist/releases/tag/v0.9.1) is now available - if you can please test with this version and report back 🙌

**Comment by mviron** [comment]
Not sure if this is an issue with the installers for 10.10 and 10.11, but was unable to use either ISO as an installer, and was unable to create the iso for 10.12

**Comment by joeselway** [comment]
I also had this issue and can confirm that an ISO for 12.7 created with 0.9.1 is now booting OK for me (again) in VMware Fusion 🥳

**Comment by ninxsoft** [comment]
#102 fixes the issue with 10.12 🎉
