### ISSUE TITLE
Build Downlods

### ISSUE THREAD

**Issue by dracinn** [ninxsoft/Mist#75]
I'd like to see where already scanned builds would be saved to make scanning time shorter.

**Comment by ninxsoft** [comment]
@dracinn I don't quite follow what you mean, are you able to expand on your issue / request?

**Comment by dracinn** [comment]
I was thinking when opening the software it starts scanning for macOS builds that once it does so a database of those builds are saved so it doesn't have to scan every time for preexisting builds, then just manually scan in future when searching for new builds. I believe this would increase efficiency especially with someone who has a wide range of builds they work with as they will be able get to downloading quickly.
