### ISSUE TITLE
Mist Download MacOS Download & Creating Boot Drive Error

### ISSUE THREAD

**Issue by KaiCarrot** [ninxsoft/Mist#76]
### :beetle: Description

Describe clearly and concisely what is not working.

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
1. Click on Installers, and Clicked on MacOS Big Sur Latest Version. Followed by the left Download button on (1*) first try, and Make Bootable USB on (2*) second try.
1. Wait for operation to complete.
1. Observe error: For (1*) first try, the download would quit with a crash report. Prompting a reopening of the app.
2. Oberve error: For (2*) second try, the installation process went well, up until the second last step of creating a bootable USB, it showed the error message in the screenshot file.

### :white_check_mark: Expected Behaviour

Using MIST, I should be able to download a working copy of MacOS High Sierra and make a bootable USB with an external USB. Using this, I could then install the OS onto a formatted Macbook Pro 2016.

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): 0.9
- macOS Version (`sw_vers`): macOS Monterey 12.2.1
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: Macbook Air M1 2020
  - Chip : M1

### :camera: Screenshots

![IMG_20230711_225333_01](https://github.com/ninxsoft/Mist/assets/123414816/ad034a91-f593-451e-8744-4a249e5e7d23)

### :information_source: Additional context

- Is this also a bug in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x:
  - Provide links to GitHub Issues
- Links to 3rd-party tools / references / documentation

**Comment by ninxsoft** [comment]
Unfortunately I am unable to reproduce a crash or the Bootable USB failure you are describing when downloading either **macOS Big Sur 11.7.9 (20G1426)** or **macOS High Sierra 10.13.6 (17G66)**

Do you have a copy of the crash log by any chance? Or is the issue reproducible and could you upload the crash log?

I am running **macOS Sonoma 14.0 beta**, however I did notice you are running **macOS Monterey 12.2.1**. Are you able to upgrade to either **macOS Monterey 12.6.8** or **macOS Ventura 13.5.1** and try again?

**Comment by KaiCarrot** [comment]
Hi Nindi,

I'm sorry to inform you that I do not have access to the same MacBook Air
anymore. It was my friend's and he left my area a month ago.

**Comment by ninxsoft** [comment]
@KaiCarrot thanks for getting back to me, and that's okay - I will go ahead close the ticket for now.

We can always re-open this if the issue pops up again 👍
