### ISSUE TITLE
Install macOS Sonoma beta.app might be damaged

### ISSUE THREAD

**Issue by master-vodawagner** [ninxsoft/Mist#77]
### :beetle: Description

Using mist to download macOS Sonoma beta 3, upon completion of the script the resulting Install macOS Sonoma beta.app has a no entry sign and running the file displays the error "You can't open application "Install macOS Sonoma beta.app" because it may be damaged or incomplete."

### :clipboard: Steps to Reproduce

1. Run the following mist-cli (1.14) command 
mist download installer 14.0 application --application-name "Install %NAME%.app" --output-directory /Users/Shared --compatible --catalog-url https://swscan.apple.com/content/catalogs/others/index-14customerseed-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz --include-betas
2. Wait for completion
3. Attempt to run the Install macOS Sonoma beta.app

I've 

### :white_check_mark: Expected Behaviour

Mist to create a valid Install macOS Sonoma beta.app

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): **1.14**
- macOS Version (`sw_vers`): **13.5**
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: **Mac14,9**
  - Chip : **Apple M2 Pro**

### :camera: Screenshots

![Screenshot 2023-07-24 at 15 56 50](https://github.com/ninxsoft/Mist/assets/39089724/a8c683b6-3781-41db-99ab-e2db106f4855)

### :information_source: Additional context

I've isolated this issue to when Mist attempts to create the installer after mounting the volume

Everything mist downloads to this tmp folder is valid, /private/tmp/com.ninxsoft.mist/042-13863
The /private/tmp/com.ninxsoft.mist/042-13863/InstallAssistant.pkg creates a valid /Applications/Install macOS Sonoma beta.app file
So the issue is purely how Mist creates the separate installer from the below logfile point

├─ Creating new installer '/Volumes/042-13863/Applications/Install macOS Sonoma beta.app'...
 ├─ Created new installer '/Volumes/042-13863/Applications/Install macOS Sonoma beta.app'

**Comment by ninxsoft** [comment]
Closing this ticket due to inactivity, will re-open if required 👍
