### ISSUE TITLE
IPSW file of macOS 12.6.1 is not shown

### ISSUE THREAD

**Issue by F1248** [ninxsoft/Mist#78]
### :beetle: Description

Mr. Macintosh [writes on his website](https://mrmacintosh.com/apple-silicon-m1-full-macos-restore-ipsw-firmware-files-database) that the latest IPSW release is macOS Monterey 12.6.1, but Mist only shows versions up to macOS 12.6.
[The link](https://updates.cdn-apple.com/2022FallFCS/fullrestores/012-66032/8D8D90C6-A876-4FFF-BBF4-D158939B3841/UniversalMac_12.6.1_21G217_Restore.ipsw) provided by Mr. Macintosh redirects to Apple's server.

### :computer: Environment

- Mist version: **Mist Version 0.9 (0.9)**
- macOS Version: **macOS 13.5 (22G74)**
- Hardware: **MacBook Air M1 (MacBookAir10,1)**

**Comment by ninxsoft** [comment]
**Mist.app** currently relies on the [IPSW Downloads API](https://ipswdownloads.docs.apiary.io/) for a list of available Firmwares, which unfortunately does not return metadata for the **macOS Monterey 12.6.1**

We have long term plans to move away from the IPSW Downloads API, but until then, we are kind of stuck unless they decide to include any missing versions.

I will go ahead and close this ticket, and will look at creating a separate project for replacing the IPSW feed 👍
