### ISSUE TITLE
Lower System Requirements

### ISSUE THREAD

**Issue by Visualwit** [ninxsoft/Mist#80]
### :bulb: Description

I am trying to run Mist on my Macbook Pro running Big Sur 11.7.9 and the app requires Monterey 12.0. I do not want to upgrade. Can you please lower the system requirements for this app?

### :white_check_mark: Proposed solution

App loads and works.

### :adhesive_bandage: Alternatives Solutions + Workarounds

None.

### :information_source: Additional context

- Would you also like to see this implemented in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x:
- Links to 3rd-party tools / references / documentation
- Screenshots / diagrams that help explain the feature request

**Comment by ninxsoft** [comment]
**Mist.app** was originally built for **macOS Monterey 12** (and later), therefore it has a lot of dependencies where there are no viable alternatives on older operating systems. For that reason I am unable to lower the operating system requirement to an older one.

Having said that, [mist-cli](https://github.com/ninxsoft/mist-cli) does support **macOS Big Sur 11**. So if you are comfortable using the command line interface, I highly recommend trying out `mist-cli`.

I will go ahead and close the issue 👍
