### ISSUE TITLE
Create OS X 10.7 and OS X 10.8 ISOs on newer macs

### ISSUE THREAD

**Issue by madsmtm** [ninxsoft/Mist#86]
### :bulb: Description

I would like the ability to create ISOs for OS X 10.7 and OS X 10.8 on newer macs.

### :adhesive_bandage: Alternatives Solutions + Workarounds

The script [createinstalliso](https://github.com/BITespresso/createinstalliso) seems to be able to do it, but maybe I'm missing a reason why it's not possible in Mist? It seems like those OSes are still running x86_64, so the architecture should not be an issue?

### :information_source: Additional context

- Could also be implemented in [mist-cli](https://github.com/ninxsoft/mist-cli). :white_check_mark:

**Comment by ninxsoft** [comment]
@madsmtm if we are specifically speaking about Intel Macs, Mist is currently relying on the `createinstallmedia` command, which is not available in the **Mac OS X Lion 10.7.5** and **OS X Mountain Lion 10.8** installer app bundles.

In theory, the `InstallESD.dmg` found in each installer app bundle could be converted to an ISO, so without promising anything, I will investigate and report back 👍

**Note:** For Apple Silicon Macs, ISOs can only be created for **macOS Big Sur 11** and later

**Comment by ninxsoft** [comment]
Good news 🥳 converting the `InstallESD.dmg` within a **Mac OS X Lion** or **OS X Mountain Lion** installer to an ISO seems to do the trick!

**See:** #101
