### ISSUE TITLE
mist 1.8 not compatible with Mojave

### ISSUE THREAD

**Issue by alvarnell** [ninxsoft/Mist#86]
% mist list -b
Library not loaded: /System/Library/Frameworks/CryptoKit.framework/Versions/A/CryptoKit
  Referenced from: /usr/local/bin/mist
  Reason: image not found
zsh: abort      mist list -b

There is no CryptoKit.framework in /System/Library, only CrytoTokenKit.framework

**Comment by ninxsoft** [comment]
`mist` version **1.8** requires **macOS Catalina 10.15**, as the [downloadTaskResumeData](https://developer.apple.com/documentation/foundation/urlerror/3329606-downloadtaskresumedata) instance property I am using (for resuming downloads) was only introduced in macOS Catalina 10.15.

Bit of a trade-off, but I can live with supporting the latest 3 operating systems (soon to be 4).

`mist` version **1.7** will continue to run on macOS Yosemite 10.10 and later

**Comment by ninxsoft** [comment]
[Mist 1.8.pkg](https://github.com/ninxsoft/Mist/releases/download/v1.8/Mist.1.8.pkg) has been updated to fail when installing on macOS 10.14 Mojave or older.

The [README.md](https://github.com/ninxsoft/Mist/commit/e1572addc4483a98c9333eccf7197b4572d45270#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and release notes have also been updated to reflect this change.

All future releases of Mist will also incorporate this logic: https://github.com/ninxsoft/Mist/commit/e1572addc4483a98c9333eccf7197b4572d45270
