### ISSUE TITLE
Missing El Capitan and Mavericks

### ISSUE THREAD

**Issue by Fred-IV** [ninxsoft/Mist#88]
### :beetle: Description:
Missing El Capitan and Mavericks from list

Describe clearly and concisely what is not working:
Missing El Capitan and Mavericks from installers.
Great program!!! Catalina can't even be downloaded from MAS anymore.
I am getting ready to build a new multi-boot USB, snd wanted to update all of my installers, but it's missing a couple.
Nice that it built Lion, because I was missing that one.

I would like to see more info in the app, or even a text export with all of the version info.
Example of my text file;
- File Name					Size			Installer	macOS Ver	Build
- Install macOS Ventura			11.97 GB		18.5.02	13.5.1		22G90
- Install macOS Monterey		12.45 GB		17.6.61	12.6.8		21G725

Include the build, and the ver of the installer, as well as the ver of macOS.

Also, since they are missing from your list, I have no idea if mine are the latest, but I have;
Install OS X El Capitan		 6.22 GB		1.7.50					15G5
Install OS X Mavericks		 5.35 GB		1.3.46					13F32

Thanks!

### :clipboard: Steps to Reproduce

1. Open; `Mist.app`
2. Click on; "Installers"
3. Wait for; List to build
4. Observe error; No errors, they are just missing form the list.
 

### :white_check_mark: Expected Behaviour
√ Mavericks and El Capitan to be in the list.

Describe what should be happening (ie. the happy path).
Mavericks and El Capitan to be in the list.

### :computer: Environment
Mac Pro A1289; Monterey 12.6.5

- Mist version (App menu ⇨ **About Mist**): **VERSION**
Version 0.9.1 (0.9.1)

- macOS Version (`sw_vers`): **VERSION BUILD**
macOS Monterey
Version 12.6.5
Mac Pro (Mid 2010)
Processor 2 x 3.46 GHz 6-Core Intel Xeon
Memory 128 GB 1333 MHZ DDR3
Startup Disk cMP WS 2010
Graphics AMD Radeon RX 580 8 GB

- Hardware (`system_profiler SPHardwareDataType`):
  Model Name:	Mac Pro
  Model Identifier:	MacPro5,1
  Processor Name:	6-Core Intel Xeon
  Processor Speed:	3.46 GHz
  Number of Processors:	2
  Total Number of Cores:	12
  L2 Cache (per Core):	256 KB
  L3 Cache (per Processor):	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	128 GB
  System Firmware Version:	9144.0.9.2.0
  OS Loader Version:	540.120.3~22
  SMC Version (system):	1.39f11
  SMC Version (processor tray):	1.39f11

- Processor
2 x 3.46 GHz 6-Core Intel Xeon
  - Model Identifier:
A1289  5,1
  - Chip :
Processor 2 x 3.46 GHz 6-Core Intel Xeon

LOL, your form has a lot of redundancy, but I filled it all out.

### :camera: Screenshots

If applicable, add screenshots to help explain the bug.
NA

### :information_source: Additional context

- Is this also a bug in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x:
  - Provide links to GitHub Issues
- Links to 3rd-party tools / references / documentation

**Comment by ninxsoft** [comment]
@Fred-IV thanks for all the info!

- **OS X Mavericks** is not available in Mist as there is no known / trusted URL provided by Apple. See: #60
- **OS X El Capitan 10.11.6 (15G31)** is available in Mist. Please ensure you have **Only show compatible versions** unchecked:
   <img width="592" alt="Mist" src="https://github.com/ninxsoft/Mist/assets/4812595/de7c1196-7dfd-42e7-afe3-444b23060392">

Regarding more info for each installer, you have two options:

- Hover over a particular installer, and all information will be visible in the tooltip:
   <img width="175" alt="Tooltip" src="https://github.com/ninxsoft/Mist/assets/4812595/521f4295-cbd4-4a10-a4f3-072bb6e13883">
- Export a list by clicking on the **Export List...** button in the bottom right corner. You can export as CSV / JSON / PLIST / YAML

**Comment by Fred-IV** [comment]
Both check boxes are not checked.
It is showing now, but for some reason, it was not when I posted the message.
Thanks!
