### ISSUE TITLE
Permissions error in Cache directory while chosing bootable disk.

### ISSUE THREAD

**Issue by ihubgit** [ninxsoft/Mist#89]
Using latest version of Mist (0.9.1.) on M2 Mac running Ventura 13.5.
Gave full disk access permissions to Mist.
Trying to get latest bootable Ventura version 13.5.1.
Erased usb to MacoS Journaled format.

Getting error msg :

> Error: You don’t have permission to save the file “042-25643” in the folder “Cache”.

**Comment by ninxsoft** [comment]
@ihubgit are you able to confirm the ownership + permissions of your **Cache** directory with the following command:

`ls -al /path/to/Mist/Cache`

The user should be your `username`, the group should be `wheel`, and the directory permissions should be `rwxr-xr-x` / `0755`.

You can find the location of your **Cache** directory in the app settings:

<img width="652" alt="Settings" src="https://github.com/ninxsoft/Mist/assets/4812595/c92c9042-9d41-4dc9-9582-e4dcf1fb2af3">

Alternatively, you can just delete the **Cache** directory manually and try downloading again 👍

**Comment by ihubgit** [comment]
when pasting that in the terminal i get no such file or directory. Do i have to create that manually?

**Comment by ihubgit** [comment]
It doesn't have a cache folder. Do i have to create one manually at that location ?
