### ISSUE TITLE
What privileges exactly Mist Privileged Helper needs?

### ISSUE THREAD

**Issue by ruchevits** [ninxsoft/Mist#95]
What privileges exactly Mist Privileged Helper needs to create a bootable installer? 

Corporate protection software blocks it:
<img width="448" alt="Screenshot 2023-10-02 at 07 43 30" src="https://github.com/ninxsoft/Mist/assets/1459783/3544ee55-a2cf-4dfb-a5f4-831c0371f266">

Any chance I can give permisions manually and re-run the 'Create bootable installer' step again?

**Comment by ninxsoft** [comment]
**Mist** requires **Full Disk Access**, as it has to download + write temporary files to disk.

You can enable this via [System Settings](https://support.apple.com/en-au/guide/mac-help/mh15217/14.0/mac/14.0):

![Full Disk Access](https://github.com/ninxsoft/Mist/raw/main/README%20Resources/Full%20Disk%20Access.png)
