### ISSUE TITLE
CLI command help is no help

### ISSUE THREAD

**Issue by indexofrefraction** [ninxsoft/Mist#96]
it would be really helpful if there were 1-2 simple command examples on how to download an installer
i'm sure reading all the documentation and help would reveal that info, but i gave up at
`mist help download installer`

**Comment by rorymurdock** [comment]
Yeah reading is much harder than taking the time to create an issue in the wrong repo. Try again after a rest. https://github.com/ninxsoft/mist-cli/blob/main/README.md#examples

**Comment by indexofrefraction** [comment]
:-D lol & peace !
it wasn't my day today ;-)
