### ISSUE TITLE
Make CLI use previously downloaded files if a process is terminated due to low disk space

### ISSUE THREAD

**Issue by danielarrington** [ninxsoft/Mist#98]
### :bulb: Description
CLI should check if a previously downloaded installer/firmware is on-disk then verify and use it instead of restarting the download automatically. This could prevent an unnecessary download for a case where there is enough disk space to download the installer/firmware files but not enough to create or copy the image later in the mist process. 

I believe this already done with the GUI so this would align the two methods.

### :information_source: Additional context

My Mac had ~50GB free after the first run failed while the `/private/tmp/com.ninxsoft.mist/042-55586` file was still on disk.
Before running the command a second time, I cleared up about ~15GB of disk space.
![Screenshot 2023-10-18 at 1 21 04 PM](https://github.com/ninxsoft/Mist/assets/36854911/f371d51e-d0ce-4ba9-9080-07821747a484)

**Comment by danielarrington** [comment]
Sorry, this should have been made in the `mist-cli` repo. This issue can be closed.

**Comment by ninxsoft** [comment]
See: https://github.com/ninxsoft/mist-cli/issues/154#issuecomment-1783713872
