### ISSUE TITLE
Pre-downloaded .pkg will be used function

### ISSUE THREAD

**Issue by Drovosek01** [ninxsoft/Mist#99]
### :bulb: Description

There are cases when the computer has poor Internet speed and downloading a .pkg file with a size of 12 GB can be a very long process or it can be interrupted due to poor Internet speed or problems with electricity.

I can download the .pkg file using a direct link (for example, from the mrmacintosh website) somewhere else (for example, on a friend's computer or at work) or using another application that supports pausing downloading and continuing downloading (for example, Free Download Manager).

I think if Mist had a function "Select .pkg with macOS on the basis of which .dmg or .iso will be created" - this would be damn convenient.
Yes, I can manually run/unpack the package and then make a .dmg with .app which will be located in the Applications folder, but if, when selecting a pre-downloaded .pkg, all the other stages of the .dmg file creation pipeline (Verifying InstallAssistant.pkg downloading and verifying InstallInfo.plist etc) will also go through, it would be damn convenient

If the same thing can be done using the official .app installer of macOS, which is usually located in the Application folder, and not to download .pkg again, then this will also be a convenient function, but in this case I do not know how the verification of this .app (that is, the files inside it) will occur, it is unlikely that Apple is somewhere distributes a list of hash sums of the original files inside the .app, but perhaps in this case it will be enough to check the digital signature of the .app and all its components so that it corresponds to Apple

### :white_check_mark: Proposed solution

I want see skip process download .pkg on my computer. Need verifying pre-downloaded .pkg and continue creating .dmg or .iso

![Screenshot 2023-10-26 at 17 58 49](https://github.com/ninxsoft/Mist/assets/29478700/59b75433-b069-41dc-9194-f4cfc54cd16e)

### :adhesive_bandage: Alternatives Solutions + Workarounds

-

### :information_source: Additional context

-

**Comment by ninxsoft** [comment]
Mist supports caching macOS Installer downloads - you can customise this in the app settings:

<img width="652" alt="Cache downloads" src="https://github.com/ninxsoft/Mist/assets/4812595/1bfc1fd3-0024-4d53-9c16-12d67e72dfd4">

Once cached, all future macOS Installer operations will skip the download portion if a valid file is detected 👍

**Comment by ninxsoft** [comment]
@Drovosek01 closing this ticket due to inactivity - will re-open if required.

**To re-iterate:** you can use the cache directory functionality to pre-populate installer packages 👍
